var searchData=
[
  ['make_5fcoherent_5fimpl',['make_coherent_impl',['../struct_eigen_1_1internal_1_1make__coherent__impl.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20a_2c_20matrix_3c_20b_5fscalar_2c_20b_5frows_2c_20b_5fcols_2c_20b_5foptions_2c_20b_5fmaxrows_2c_20b_5fmaxcols_20_3e_20_3e',['make_coherent_impl&lt; A, Matrix&lt; B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols &gt; &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_a_00_01_matrix_3_01_b___scalar_00_01_b___r2332686f3180c2f2d848d1b5e8319450.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20matrix_3c_20a_5fscalar_2c_20a_5frows_2c_20a_5fcols_2c_20a_5foptions_2c_20a_5fmaxrows_2c_20a_5fmaxcols_20_3e_2c_20b_20_3e',['make_coherent_impl&lt; Matrix&lt; A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols &gt;, B &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_matrix_3_01_a___scalar_00_01_a___rows_00_0aa8f55819fa60ac5751cc2cbbaa58000.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20matrix_3c_20a_5fscalar_2c_20a_5frows_2c_20a_5fcols_2c_20a_5foptions_2c_20a_5fmaxrows_2c_20a_5fmaxcols_20_3e_2c_20matrix_3c_20b_5fscalar_2c_20b_5frows_2c_20b_5fcols_2c_20b_5foptions_2c_20b_5fmaxrows_2c_20b_5fmaxcols_20_3e_20_3e',['make_coherent_impl&lt; Matrix&lt; A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols &gt;, Matrix&lt; B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols &gt; &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_matrix_3_01_a___scalar_00_01_a___rows_00_02c107ffcc218caac688e11f3e382ff61.html',1,'Eigen::internal']]],
  ['make_5fproper_5fmatrix_5ftype',['make_proper_matrix_type',['../class_eigen_1_1internal_1_1make__proper__matrix__type.html',1,'Eigen::internal']]],
  ['make_5fproper_5fmatrix_5ftype_3c_20scalar_2c_20rows_2c_20hdim_2c_20options_20_3e',['make_proper_matrix_type&lt; Scalar, Rows, HDim, Options &gt;',['../class_eigen_1_1internal_1_1make__proper__matrix__type.html',1,'Eigen::internal']]],
  ['make_5ftype_5flist',['make_type_list',['../struct_eigen_1_1internal_1_1make__type__list.html',1,'Eigen::internal']]],
  ['make_5ftype_5flist_3c_3e',['make_type_list&lt;&gt;',['../struct_eigen_1_1internal_1_1make__type__list_3_4.html',1,'Eigen::internal']]],
  ['makecomplexop',['MakeComplexOp',['../struct_make_complex_op.html',1,'']]],
  ['makepointer',['MakePointer',['../struct_eigen_1_1internal_1_1traits_3_01_tensor_forced_eval_op_3_01_xpr_type_00_01_make_pointer___01_4_01_4_1_1_make_pointer.html',1,'Eigen::internal::traits&lt; TensorForcedEvalOp&lt; XprType, MakePointer_ &gt; &gt;::MakePointer&lt; T &gt;'],['../struct_eigen_1_1_make_pointer.html',1,'Eigen::MakePointer&lt; T &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_tensor_reduction_op_3_01_op_00_01_dims_00_01_xpr_type_00c39382462f4a2e2ae6af6fe0f8aab669.html',1,'Eigen::internal::traits&lt; TensorReductionOp&lt; Op, Dims, XprType, MakePointer_ &gt; &gt;::MakePointer&lt; T &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_tensor_map_3_01_plain_object_type_00_01_options___00_01_2ffe711dc868f2af95478b5bf448510f.html',1,'Eigen::internal::traits&lt; TensorMap&lt; PlainObjectType, Options_, MakePointer_ &gt; &gt;::MakePointer&lt; T &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_tensor_3_01_scalar___00_01_num_indices___00_01_options__a867f84013967cd95c2f883b666f993d.html',1,'Eigen::internal::traits&lt; Tensor&lt; Scalar_, NumIndices_, Options_, IndexType_ &gt; &gt;::MakePointer&lt; T &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_tensor_fixed_size_3_01_scalar___00_01_dimensions_00_01_oec1d8e96ca2c261993f05f9c1095a180.html',1,'Eigen::internal::traits&lt; TensorFixedSize&lt; Scalar_, Dimensions, Options_, IndexType_ &gt; &gt;::MakePointer&lt; T &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_tensor_eval_to_op_3_01_xpr_type_00_01_make_pointer___01_4_01_4_1_1_make_pointer.html',1,'Eigen::internal::traits&lt; TensorEvalToOp&lt; XprType, MakePointer_ &gt; &gt;::MakePointer&lt; T &gt;']]],
  ['makepointer_3c_20eigen_3a_3atriplet_20_3e',['MakePointer&lt; Eigen::Triplet &gt;',['../struct_eigen_1_1_make_pointer.html',1,'Eigen']]],
  ['mandelbrotthread',['MandelbrotThread',['../class_mandelbrot_thread.html',1,'']]],
  ['mandelbrotwidget',['MandelbrotWidget',['../class_mandelbrot_widget.html',1,'']]],
  ['map',['Map',['../group___core___module.html#class_eigen_1_1_map',1,'Eigen']]],
  ['map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e',['Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt;',['../group___geometry___module.html#class_eigen_1_1_map_3_01const_01_quaternion_3_01___scalar_01_4_00_01___options_01_4',1,'Eigen']]],
  ['map_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e',['Map&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../class_eigen_1_1_map_3_01const_01_sparse_matrix_3_01_mat_scalar_00_01_mat_options_00_01_mat_index4032bba20cf92aab8bcf07e926e15a4f.html',1,'Eigen']]],
  ['map_3c_20permutationmatrix_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20_5fstorageindex_20_3e_2c_20_5fpacketaccess_20_3e',['Map&lt; PermutationMatrix&lt; SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex &gt;, _PacketAccess &gt;',['../class_eigen_1_1_map_3_01_permutation_matrix_3_01_size_at_compile_time_00_01_max_size_at_compile_2f9d18bf0084dbfb13fbbfe14adaf22d.html',1,'Eigen']]],
  ['map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e',['Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt;',['../group___geometry___module.html#class_eigen_1_1_map_3_01_quaternion_3_01___scalar_01_4_00_01___options_01_4',1,'Eigen']]],
  ['map_3c_20sparsematrix_3c_20_5fscalar_2c_20_5fflags_2c_20_5fstorageindex_20_3e_20_3e',['Map&lt; SparseMatrix&lt; _Scalar, _Flags, _StorageIndex &gt; &gt;',['../group___core___module.html',1,'Eigen']]],
  ['map_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e',['Map&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt;',['../group___sparse_core___module.html#class_eigen_1_1_map_3_01_sparse_matrix_3_01_mat_scalar_00_01_mat_options_00_01_mat_index_01_4_002c859b470cc9e43a031929bd752a93e6',1,'Eigen']]],
  ['map_3c_20transpositions_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20_5fstorageindex_20_3e_2c_20packetaccess_20_3e',['Map&lt; Transpositions&lt; SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex &gt;, PacketAccess &gt;',['../class_eigen_1_1_map_3_01_transpositions_3_01_size_at_compile_time_00_01_max_size_at_compile_timecc993082d7c0ba51ca94b27e97da8dd3.html',1,'Eigen']]],
  ['map_5fsize',['map_size',['../structmap__size.html',1,'']]],
  ['map_5fsize_3c_2010_20_3e',['map_size&lt; 10 &gt;',['../structmap__size_3_0110_01_4.html',1,'']]],
  ['map_5fsize_3c_2011_20_3e',['map_size&lt; 11 &gt;',['../structmap__size_3_0111_01_4.html',1,'']]],
  ['map_5fsize_3c_2012_20_3e',['map_size&lt; 12 &gt;',['../structmap__size_3_0112_01_4.html',1,'']]],
  ['map_5fsize_3c_2013_20_3e',['map_size&lt; 13 &gt;',['../structmap__size_3_0113_01_4.html',1,'']]],
  ['mapbase',['MapBase',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['MapBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20derived_20_3e',['MapBase&lt; Derived &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20derived_2c_20readonlyaccessors_20_3e',['MapBase&lt; Derived, ReadOnlyAccessors &gt;',['../group___core___module.html#class_eigen_1_1_map_base_3_01_derived_00_01_read_only_accessors_01_4',1,'Eigen']]],
  ['mapbase_3c_20derived_2c_20writeaccessors_20_3e',['MapBase&lt; Derived, WriteAccessors &gt;',['../group___core___module.html#class_eigen_1_1_map_base_3_01_derived_00_01_write_accessors_01_4',1,'Eigen']]],
  ['mapbase_3c_20map_3c_20plainobjecttype_2c_20mapoptions_2c_20stridetype_20_3e_20_3e',['MapBase&lt; Map&lt; PlainObjectType, MapOptions, StrideType &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_5fevaluator',['mapbase_evaluator',['../struct_eigen_1_1internal_1_1mapbase__evaluator.html',1,'Eigen::internal']]],
  ['mapbase_5fevaluator_3c_20block_3c_20argtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_2c_20block_3c_20argtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_3a_3aplainobject_20_3e',['mapbase_evaluator&lt; Block&lt; ArgType, BlockRows, BlockCols, InnerPanel &gt;, Block&lt; ArgType, BlockRows, BlockCols, InnerPanel &gt;::PlainObject &gt;',['../struct_eigen_1_1internal_1_1mapbase__evaluator.html',1,'Eigen::internal']]],
  ['mapbase_5fevaluator_3c_20map_3c_20plainobjecttype_2c_20mapoptions_2c_20stridetype_20_3e_2c_20plainobjecttype_20_3e',['mapbase_evaluator&lt; Map&lt; PlainObjectType, MapOptions, StrideType &gt;, PlainObjectType &gt;',['../struct_eigen_1_1internal_1_1mapbase__evaluator.html',1,'Eigen::internal']]],
  ['mapbase_5fevaluator_3c_20ref_3c_20plainobjecttype_2c_20refoptions_2c_20stridetype_20_3e_2c_20plainobjecttype_20_3e',['mapbase_evaluator&lt; Ref&lt; PlainObjectType, RefOptions, StrideType &gt;, PlainObjectType &gt;',['../struct_eigen_1_1internal_1_1mapbase__evaluator.html',1,'Eigen::internal']]],
  ['mappedskylinematrix',['MappedSkylineMatrix',['../class_eigen_1_1_mapped_skyline_matrix.html',1,'Eigen']]],
  ['mappedsparsematrix',['MappedSparseMatrix',['../class_eigen_1_1_mapped_sparse_matrix.html',1,'Eigen']]],
  ['mappedsparsematrix_3c_20scalar_2c_20colmajor_2c_20storageindex_20_3e',['MappedSparseMatrix&lt; Scalar, ColMajor, StorageIndex &gt;',['../class_eigen_1_1_mapped_sparse_matrix.html',1,'Eigen']]],
  ['mappedsupernodalmatrix',['MappedSuperNodalMatrix',['../group___sparse_l_u___module.html#class_eigen_1_1internal_1_1_mapped_super_nodal_matrix',1,'Eigen::internal']]],
  ['mappedsupernodalmatrix_3c_20scalar_2c_20storageindex_20_3e',['MappedSuperNodalMatrix&lt; Scalar, StorageIndex &gt;',['../group___sparse_l_u___module.html',1,'Eigen::internal']]],
  ['mapstaticmethods_5fimpl',['mapstaticmethods_impl',['../structmapstaticmethods__impl.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20false_2c_20isvector_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, false, IsVector &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01false_00_01_is_vector_01_4.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20true_2c_20false_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, true, false &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01true_00_01false_01_4.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20true_2c_20true_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, true, true &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01true_00_01true_01_4.html',1,'']]],
  ['mat_5fcomplex_5fsplit_5ft',['mat_complex_split_t',['../group___m_a_t.html#structmat__complex__split__t',1,'']]],
  ['mat_5fsparse_5ft',['mat_sparse_t',['../group___m_a_t.html#structmat__sparse__t',1,'']]],
  ['match',['match',['../struct_eigen_1_1internal_1_1traits_3_01_ref_3_01_sparse_vector_3_01_mat_scalar_00_01_mat_options4b581d834744f71c5c7313d6641690e6.html',1,'Eigen::internal::traits&lt; Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, _Options, _StrideType &gt; &gt;::match&lt; Derived &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_ref_3_01_sparse_matrix_3_01_mat_scalar_00_01_mat_optionsc6ef0ce4e339306d76a1e27f17721ded.html',1,'Eigen::internal::traits&lt; Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, _Options, _StrideType &gt; &gt;::match&lt; Derived &gt;'],['../struct_eigen_1_1internal_1_1traits_3_01_ref_3_01___plain_object_type_00_01___options_00_01___stride_type_01_4_01_4_1_1match.html',1,'Eigen::internal::traits&lt; Ref&lt; _PlainObjectType, _Options, _StrideType &gt; &gt;::match&lt; Derived &gt;']]],
  ['matfilereader',['MatFileReader',['../class_mat_file_reader.html',1,'']]],
  ['matrix',['Matrix',['../group___core___module.html#class_eigen_1_1_matrix',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_28_7erowmajor_29_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; ComplexScalar, ColsAtCompileTime, 1, Options &amp;(~RowMajor), MaxColsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_7erowmajor_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; ComplexScalar, ColsAtCompileTime, 1, Options &amp;~RowMajor, MaxColsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20dynamic_2c_20dynamic_2c_200_2c_20matrixtype_3a_3arowsatcompiletime_2c_20matrixtype_3a_3acolsatcompiletime_20_3e',['Matrix&lt; ComplexScalar, Dynamic, Dynamic, 0, MatrixType::RowsAtCompileTime, MatrixType::ColsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20rowsatcompiletime_2c_20colsatcompiletime_2c_20options_2c_20maxrowsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20float_2c_202_2c_202_2c_20dontalign_20_3e',['Matrix&lt; float, 2, 2, DontAlign &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20float_2c_208_2c_201_20_3e',['Matrix&lt; float, 8, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20int_2c_201_2c_20matrixtype_3a_3acolsatcompiletime_20_3e',['Matrix&lt; int, 1, MatrixType::ColsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20int_2c_20matrixtype_3a_3arowsatcompiletime_2c_201_20_3e',['Matrix&lt; int, MatrixType::RowsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20realscalar_2c_20dynamic_2c_201_20_3e',['Matrix&lt; RealScalar, Dynamic, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20realscalar_2c_20dynamic_2c_20dynamic_2c_20colmajor_20_3e',['Matrix&lt; RealScalar, Dynamic, Dynamic, ColMajor &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20roottype_2c_20_5fdeg_2c_201_20_3e',['Matrix&lt; RootType, _Deg, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_201_2c_20rowsatcompiletime_2c_20rowmajor_2c_201_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_201_2c_20size_2c_20options_7crowmajor_2c_201_2c_20maxsize_20_3e',['Matrix&lt; Scalar, 1, Size, Options|RowMajor, 1, MaxSize &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_203_2c_201_20_3e',['Matrix&lt; Scalar, 3, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20ambientdimatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, AmbientDimAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20ambientdimatcompiletime_2c_201_2c_20options_20_3e',['Matrix&lt; Scalar, AmbientDimAtCompileTime, 1, Options &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_7erowmajor_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, 1, Options &amp;~RowMajor, MaxColsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_20colsatcompiletime_2c_20matrixoptions_2c_20maxcolsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_20rowsatcompiletime_2c_20options_2c_20maxcolsatcompiletime_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_20rowsatcompiletime_2c_20troptions_2c_20maxcolsatcompiletime_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, RowsAtCompileTime, TrOptions, MaxColsAtCompileTime, MaxRowsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20deg_2c_201_20_3e',['Matrix&lt; Scalar, Deg, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20deg_5f1_2c_201_20_3e',['Matrix&lt; Scalar, Deg_1, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20diagsizeatcompiletime_2c_20diagsizeatcompiletime_2c_20matrixoptions_2c_20maxdiagsizeatcompiletime_2c_20maxdiagsizeatcompiletime_20_3e',['Matrix&lt; Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dim_2c_201_20_3e',['Matrix&lt; Scalar, Dim, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dynamic_2c_201_20_3e',['Matrix&lt; Scalar, Dynamic, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dynamic_2c_20dynamic_20_3e',['Matrix&lt; Scalar, Dynamic, Dynamic &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20index_28ambientdimatcompiletime_29_3d_3ddynamic_20_3f_20dynamic_20_3aindex_28ambientdimatcompiletime_29_2b1_2c_201_2c_20options_20_3e',['Matrix&lt; Scalar, Index(AmbientDimAtCompileTime)==Dynamic ? Dynamic :Index(AmbientDimAtCompileTime)+1, 1, Options &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20rowsatcompiletime_2c_201_2c_200_2c_20maxrowsatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, RowsAtCompileTime, 1, 0, MaxRowsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20rowsatcompiletime_2c_20rowsatcompiletime_2c_20matrixoptions_2c_20maxrowsatcompiletime_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20size_2c_20size_2c_20colmajor_2c_20maxcolsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; Scalar, Size, Size, ColMajor, MaxColsAtCompileTime, MaxColsAtCompileTime &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20sizeminusone_2c_201_2c_20options_20_26_7erowmajor_2c_20maxsizeminusone_2c_201_20_3e',['Matrix&lt; Scalar, SizeMinusOne, 1, Options &amp;~RowMajor, MaxSizeMinusOne, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20storageindex_2c_201_2c_20eigen_5fsize_5fmin_5fprefer_5fdynamic_28colsatcompiletime_2c_20rowsatcompiletime_29_2c_20rowmajor_2c_201_2c_20eigen_5fsize_5fmin_5fprefer_5ffixed_28maxcolsatcompiletime_2c_20maxrowsatcompiletime_29_3e',['Matrix&lt; StorageIndex, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime, MaxRowsAtCompileTime)&gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20storageindex_2c_20dynamic_2c_201_20_3e',['Matrix&lt; StorageIndex, Dynamic, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_3c_20storageindex_2c_20matrixtype_3a_3arowsatcompiletime_2c_201_20_3e',['Matrix&lt; StorageIndex, MatrixType::RowsAtCompileTime, 1 &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrix_5fexp_5fcomputeuv',['matrix_exp_computeUV',['../struct_eigen_1_1internal_1_1matrix__exp__compute_u_v.html',1,'Eigen::internal']]],
  ['matrix_5fexp_5fcomputeuv_3c_20matrixtype_2c_20double_20_3e',['matrix_exp_computeUV&lt; MatrixType, double &gt;',['../struct_eigen_1_1internal_1_1matrix__exp__compute_u_v_3_01_matrix_type_00_01double_01_4.html',1,'Eigen::internal']]],
  ['matrix_5fexp_5fcomputeuv_3c_20matrixtype_2c_20float_20_3e',['matrix_exp_computeUV&lt; MatrixType, float &gt;',['../struct_eigen_1_1internal_1_1matrix__exp__compute_u_v_3_01_matrix_type_00_01float_01_4.html',1,'Eigen::internal']]],
  ['matrix_5fexp_5fcomputeuv_3c_20matrixtype_2c_20long_20double_20_3e',['matrix_exp_computeUV&lt; MatrixType, long double &gt;',['../struct_eigen_1_1internal_1_1matrix__exp__compute_u_v_3_01_matrix_type_00_01long_01double_01_4.html',1,'Eigen::internal']]],
  ['matrix_5ffunction_5fcompute',['matrix_function_compute',['../struct_eigen_1_1internal_1_1matrix__function__compute.html',1,'Eigen::internal']]],
  ['matrix_5ffunction_5fcompute_3c_20matrixtype_2c_200_20_3e',['matrix_function_compute&lt; MatrixType, 0 &gt;',['../struct_eigen_1_1internal_1_1matrix__function__compute_3_01_matrix_type_00_010_01_4.html',1,'Eigen::internal']]],
  ['matrix_5ffunction_5fcompute_3c_20matrixtype_2c_201_20_3e',['matrix_function_compute&lt; MatrixType, 1 &gt;',['../struct_eigen_1_1internal_1_1matrix__function__compute_3_01_matrix_type_00_011_01_4.html',1,'Eigen::internal']]],
  ['matrix_5flog_5fmax_5fpade_5fdegree',['matrix_log_max_pade_degree',['../struct_eigen_1_1internal_1_1matrix__log__max__pade__degree.html',1,'Eigen::internal']]],
  ['matrix_5flog_5fmin_5fpade_5fdegree',['matrix_log_min_pade_degree',['../struct_eigen_1_1internal_1_1matrix__log__min__pade__degree.html',1,'Eigen::internal']]],
  ['matrix_5fsqrt_5fcompute',['matrix_sqrt_compute',['../struct_eigen_1_1internal_1_1matrix__sqrt__compute.html',1,'Eigen::internal']]],
  ['matrix_5fsqrt_5fcompute_3c_20matrixtype_2c_200_20_3e',['matrix_sqrt_compute&lt; MatrixType, 0 &gt;',['../struct_eigen_1_1internal_1_1matrix__sqrt__compute_3_01_matrix_type_00_010_01_4.html',1,'Eigen::internal']]],
  ['matrix_5fsqrt_5fcompute_3c_20matrixtype_2c_201_20_3e',['matrix_sqrt_compute&lt; MatrixType, 1 &gt;',['../struct_eigen_1_1internal_1_1matrix__sqrt__compute_3_01_matrix_type_00_011_01_4.html',1,'Eigen::internal']]],
  ['matrix_5fswap_5fimpl',['matrix_swap_impl',['../struct_eigen_1_1internal_1_1matrix__swap__impl.html',1,'Eigen::internal']]],
  ['matrix_5fswap_5fimpl_3c_20matrixtypea_2c_20matrixtypeb_2c_20true_20_3e',['matrix_swap_impl&lt; MatrixTypeA, MatrixTypeB, true &gt;',['../struct_eigen_1_1internal_1_1matrix__swap__impl_3_01_matrix_type_a_00_01_matrix_type_b_00_01true_01_4.html',1,'Eigen::internal']]],
  ['matrix_5ftype_5ftimes_5fscalar_5ftype',['matrix_type_times_scalar_type',['../struct_eigen_1_1internal_1_1matrix__type__times__scalar__type.html',1,'Eigen::internal']]],
  ['matrixbase',['MatrixBase',['../group___core___module.html#class_eigen_1_1_matrix_base',1,'Eigen']]],
  ['matrixbase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e',['MatrixBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrixbase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e',['MatrixBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrixbase_3c_20solve_3c_20decomposition_2c_20rhstype_20_3e_20_3e',['MatrixBase&lt; Solve&lt; Decomposition, RhsType &gt; &gt;',['../group___core___module.html',1,'Eigen']]],
  ['matrixcomplexpowerreturnvalue',['MatrixComplexPowerReturnValue',['../class_eigen_1_1_matrix_complex_power_return_value.html',1,'Eigen']]],
  ['matrixexponentialreturnvalue',['MatrixExponentialReturnValue',['../struct_eigen_1_1_matrix_exponential_return_value.html',1,'Eigen']]],
  ['matrixexponentialscalingop',['MatrixExponentialScalingOp',['../struct_eigen_1_1internal_1_1_matrix_exponential_scaling_op.html',1,'Eigen::internal']]],
  ['matrixfunctionatomic',['MatrixFunctionAtomic',['../class_eigen_1_1internal_1_1_matrix_function_atomic.html',1,'Eigen::internal']]],
  ['matrixfunctionreturnvalue',['MatrixFunctionReturnValue',['../class_eigen_1_1_matrix_function_return_value.html',1,'Eigen']]],
  ['matrixlogarithmatomic',['MatrixLogarithmAtomic',['../class_eigen_1_1internal_1_1_matrix_logarithm_atomic.html',1,'Eigen::internal']]],
  ['matrixlogarithmreturnvalue',['MatrixLogarithmReturnValue',['../class_eigen_1_1_matrix_logarithm_return_value.html',1,'Eigen']]],
  ['matrixmarketiterator',['MatrixMarketIterator',['../class_eigen_1_1_matrix_market_iterator.html',1,'Eigen']]],
  ['matrixpower',['MatrixPower',['../class_eigen_1_1_matrix_power.html',1,'Eigen']]],
  ['matrixpoweratomic',['MatrixPowerAtomic',['../class_eigen_1_1_matrix_power_atomic.html',1,'Eigen']]],
  ['matrixpowerparenthesesreturnvalue',['MatrixPowerParenthesesReturnValue',['../class_eigen_1_1_matrix_power_parentheses_return_value.html',1,'Eigen']]],
  ['matrixpowerreturnvalue',['MatrixPowerReturnValue',['../class_eigen_1_1_matrix_power_return_value.html',1,'Eigen']]],
  ['matrixreplacement',['MatrixReplacement',['../class_matrix_replacement.html',1,'']]],
  ['matrixsquarerootreturnvalue',['MatrixSquareRootReturnValue',['../class_eigen_1_1_matrix_square_root_return_value.html',1,'Eigen']]],
  ['matrixwrapper',['MatrixWrapper',['../group___core___module.html#class_eigen_1_1_matrix_wrapper',1,'Eigen']]],
  ['matrixxpr',['MatrixXpr',['../struct_eigen_1_1_matrix_xpr.html',1,'Eigen']]],
  ['matvar_5finternal',['matvar_internal',['../structmatvar__internal.html',1,'']]],
  ['matvar_5ft',['matvar_t',['../group___m_a_t.html#structmatvar__t',1,'']]],
  ['max_5fcoeff_5fvisitor',['max_coeff_visitor',['../struct_eigen_1_1internal_1_1max__coeff__visitor.html',1,'Eigen::internal']]],
  ['max_5fn_5f1',['max_n_1',['../struct_eigen_1_1max__n__1.html',1,'Eigen']]],
  ['max_5fn_5f1_3c_200_20_3e',['max_n_1&lt; 0 &gt;',['../struct_eigen_1_1max__n__1_3_010_01_4.html',1,'Eigen']]],
  ['maxreducer',['MaxReducer',['../struct_eigen_1_1internal_1_1_max_reducer.html',1,'Eigen::internal']]],
  ['maxsizevector',['MaxSizeVector',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['maxsizevector_3c_20eigen_3a_3aeventcount_3a_3awaiter_20_3e',['MaxSizeVector&lt; Eigen::EventCount::Waiter &gt;',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['maxsizevector_3c_20eigen_3a_3arunqueue_20_2a_3e',['MaxSizeVector&lt; Eigen::RunQueue *&gt;',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['maxsizevector_3c_20thread_20_2a_3e',['MaxSizeVector&lt; Thread *&gt;',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['maxsizevector_3c_20unsigned_20_3e',['MaxSizeVector&lt; unsigned &gt;',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['maxsizevector_3c_20waiter_20_2a_3e',['MaxSizeVector&lt; Waiter *&gt;',['../class_eigen_1_1_max_size_vector.html',1,'Eigen']]],
  ['meanreducer',['MeanReducer',['../struct_eigen_1_1internal_1_1_mean_reducer.html',1,'Eigen::internal']]],
  ['measure_5fall_5fpot_5fsizes_5faction_5ft',['measure_all_pot_sizes_action_t',['../structmeasure__all__pot__sizes__action__t.html',1,'']]],
  ['measure_5fdefault_5fsizes_5faction_5ft',['measure_default_sizes_action_t',['../structmeasure__default__sizes__action__t.html',1,'']]],
  ['mem_5fitem',['mem_item',['../structmem__item.html',1,'']]],
  ['mem_5fzone',['mem_zone',['../structmem__zone.html',1,'']]],
  ['member_5flpnorm',['member_lpnorm',['../struct_eigen_1_1internal_1_1member__lpnorm.html',1,'Eigen::internal']]],
  ['member_5fredux',['member_redux',['../struct_eigen_1_1internal_1_1member__redux.html',1,'Eigen::internal']]],
  ['meta_5fleast_5fcommon_5fmultiple',['meta_least_common_multiple',['../struct_eigen_1_1internal_1_1meta__least__common__multiple.html',1,'Eigen::internal']]],
  ['meta_5fleast_5fcommon_5fmultiple_3c_20a_2c_20b_2c_20k_2c_20true_20_3e',['meta_least_common_multiple&lt; A, B, K, true &gt;',['../struct_eigen_1_1internal_1_1meta__least__common__multiple_3_01_a_00_01_b_00_01_k_00_01true_01_4.html',1,'Eigen::internal']]],
  ['meta_5fno',['meta_no',['../struct_eigen_1_1internal_1_1meta__no.html',1,'Eigen::internal']]],
  ['meta_5fsqrt',['meta_sqrt',['../class_eigen_1_1internal_1_1meta__sqrt.html',1,'Eigen::internal']]],
  ['meta_5fsqrt_3c_20y_2c_20infx_2c_20supx_2c_20true_20_3e',['meta_sqrt&lt; Y, InfX, SupX, true &gt;',['../class_eigen_1_1internal_1_1meta__sqrt_3_01_y_00_01_inf_x_00_01_sup_x_00_01true_01_4.html',1,'Eigen::internal']]],
  ['meta_5fyes',['meta_yes',['../struct_eigen_1_1internal_1_1meta__yes.html',1,'Eigen::internal']]],
  ['metisordering',['MetisOrdering',['../class_eigen_1_1_metis_ordering.html',1,'Eigen']]],
  ['mgh09_5ffunctor',['MGH09_functor',['../struct_m_g_h09__functor.html',1,'']]],
  ['mgh10_5ffunctor',['MGH10_functor',['../struct_m_g_h10__functor.html',1,'']]],
  ['mgh17_5ffunctor',['MGH17_functor',['../struct_m_g_h17__functor.html',1,'']]],
  ['min_5fcoeff_5fvisitor',['min_coeff_visitor',['../struct_eigen_1_1internal_1_1min__coeff__visitor.html',1,'Eigen::internal']]],
  ['minimizer_5fhelper1',['minimizer_helper1',['../struct_eigen_1_1internal_1_1minimizer__helper1.html',1,'Eigen::internal']]],
  ['minimizer_5fhelper2',['minimizer_helper2',['../struct_eigen_1_1internal_1_1minimizer__helper2.html',1,'Eigen::internal']]],
  ['minmaxbottomvalue',['MinMaxBottomValue',['../struct_eigen_1_1internal_1_1_min_max_bottom_value.html',1,'Eigen::internal']]],
  ['minmaxbottomvalue_3c_20t_2c_20false_2c_20false_20_3e',['MinMaxBottomValue&lt; T, false, false &gt;',['../struct_eigen_1_1internal_1_1_min_max_bottom_value_3_01_t_00_01false_00_01false_01_4.html',1,'Eigen::internal']]],
  ['minmaxbottomvalue_3c_20t_2c_20false_2c_20true_20_3e',['MinMaxBottomValue&lt; T, false, true &gt;',['../struct_eigen_1_1internal_1_1_min_max_bottom_value_3_01_t_00_01false_00_01true_01_4.html',1,'Eigen::internal']]],
  ['minmaxbottomvalue_3c_20t_2c_20true_2c_20false_20_3e',['MinMaxBottomValue&lt; T, true, false &gt;',['../struct_eigen_1_1internal_1_1_min_max_bottom_value_3_01_t_00_01true_00_01false_01_4.html',1,'Eigen::internal']]],
  ['minreducer',['MinReducer',['../struct_eigen_1_1internal_1_1_min_reducer.html',1,'Eigen::internal']]],
  ['minres',['MINRES',['../group___iterative_linear_solvers___module.html#class_eigen_1_1_m_i_n_r_e_s',1,'Eigen']]],
  ['misra1a_5ffunctor',['misra1a_functor',['../structmisra1a__functor.html',1,'']]],
  ['misra1d_5ffunctor',['misra1d_functor',['../structmisra1d__functor.html',1,'']]],
  ['mixed_5fperf_5fanalyzer',['Mixed_Perf_Analyzer',['../class_mixed___perf___analyzer.html',1,'']]],
  ['mpreal',['mpreal',['../classmpfr_1_1mpreal.html',1,'mpfr']]],
  ['mtl4_5finterface',['mtl4_interface',['../classmtl4__interface.html',1,'']]],
  ['mul_5fassign_5fop',['mul_assign_op',['../struct_eigen_1_1internal_1_1mul__assign__op.html',1,'Eigen::internal']]],
  ['my_5fexception',['my_exception',['../structmy__exception.html',1,'']]],
  ['my_5ffunctor',['my_functor',['../structmy__functor.html',1,'']]],
  ['myclassa',['MyClassA',['../class_my_class_a.html',1,'']]],
  ['mygenerator',['MyGenerator',['../struct_my_generator.html',1,'']]],
  ['mystruct',['MyStruct',['../struct_my_struct.html',1,'']]],
  ['myvectortype',['MyVectorType',['../class_my_vector_type.html',1,'']]]
];
