Transformation Class Reference
#include <Transformation.h>
Public Member Functions
Transformation ()
constructor
~Transformation ()
destructor
Eigen::Matrix3d MatNedToBody (Float64 phi, Float64 theta, Float64 psi)
tranformation matrix from NED system to body fixed system
Eigen::Matrix3d MatBodyToNED (Eigen::Matrix3d MatNedToBody)
tranformation matrix from Body system to NED system
Eigen::Matrix3d MatNEDToTrajectory (Float64 Gamma, Float64 chi)
tranformation matrix from NED system to trajectory system
Eigen::Matrix3d MatAeroToBody (Float64 Alpha, Float64 Beta)
tranformation matrix from aerodynamic system to body fixed system
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
Transformation class provides transformation matrices for flightmechanical coordinate sytems
Definition at line 19 of file Transformation.h.
Constructor & Destructor Documentation
Transformation()
Transformation::Transformation ()
constructor
Definition at line 3 of file Transformation.cpp.
 Transformation()
Transformation::~Transformation ()
destructor
Definition at line 7 of file Transformation.cpp.
Member Function Documentation
MatAeroToBody()
Eigen::Matrix3d Transformation::MatAeroToBody (Float64 Alpha, Float64 Beta)
tranformation matrix from aerodynamic system to body fixed system
Parameters
Alpha angle of attack
Beta angle of sideslip
Definition at line 38 of file Transformation.cpp.
Referenced by AerodynamicTest(), and UnitTest1::TEST_CLASS().
MatBodyToNED()
Eigen::Matrix3d Transformation::MatBodyToNED (Eigen::Matrix3d MatNedToBody)
tranformation matrix from Body system to NED system
Parameters
MatNedToBody invers matrix
Definition at line 20 of file Transformation.cpp.
Referenced by Trajectory6Dof::integrationTrajectory(), and flawlessNavigation::updateNavigation().
MatNedToBody()
Eigen::Matrix3d Transformation::MatNedToBody (Float64 phi, Float64 theta, Float64 psi)
tranformation matrix from NED system to body fixed system
Parameters
phi roll angle
theta pitch angle
psi heading angle
Definition at line 11 of file Transformation.cpp.
Referenced by AerodynamicTest(), GuidanceTest(), Trajectory6Dof::integrationTrajectory(), UnitTest1::TEST_CLASS(), and flawlessNavigation::updateNavigation().
MatNEDToTrajectory()
Eigen::Matrix3d Transformation::MatNEDToTrajectory (Float64 Gamma, Float64 chi)
tranformation matrix from NED system to trajectory system
Parameters
Gamma
chi azimuth
Definition at line 27 of file Transformation.cpp.
Referenced by GuidanceTest(), Trajectory6Dof::integrationTrajectory(), UnitTest1::TEST_CLASS(), and flawlessNavigation::updateNavigation().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/Transformation.h
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/Transformation.cpp