Trajectory6Dof Class Reference
#include <Trajectory6DoF.h>
Public Member Functions
Trajectory6Dof (SimDPreference &SimPref)
constructor
~Trajectory6Dof ()
destructor
virtual void initTrajectory (Float64 &FlightTime, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, AircraftStruct &AircraftData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
initalize trajectory
virtual void updateTrajectory (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
calculate trajectory
void integrationTrajectory (AirframeStruct &AirframeData, IMUStruct &IMUData, NavigationStruct &NavData)
integrate accelerations and calculate new flight states
void log6DofData ()
log 6Dof Trajectory data
void initLog6Dof (Float64 &FlightTime, IMUStruct &IMUData, NavigationStruct &NavData, ActuatorStruct &ActuatorData)
define output for trajectory 6D0f
Detailed Description
Definition at line 23 of file Trajectory6DoF.h.
Constructor & Destructor Documentation
Trajectory6Dof()
Trajectory6Dof::Trajectory6Dof (SimDPreference & SimPref)
constructor
Parameters
SimPref mode selection for trajectory
Definition at line 3 of file Trajectory6DoF.cpp.
 Trajectory6Dof()
Trajectory6Dof::~Trajectory6Dof ()
destructor
Definition at line 18 of file Trajectory6DoF.cpp.
Member Function Documentation
initLog6Dof()
void Trajectory6Dof::initLog6Dof (Float64 & FlightTime, IMUStruct & IMUData, NavigationStruct & NavData, ActuatorStruct & ActuatorData)
define output for trajectory 6D0f
Parameters
FlightTime flighttime
IMUData accelerations and rotatory rates
NavData structure that stores position and velocity
ActuatorData aircraft control deflections
Definition at line 142 of file Trajectory6DoF.cpp.
Referenced by initTrajectory().
initTrajectory()
void Trajectory6Dof::initTrajectory (Float64 & FlightTime, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, AircraftStruct & AircraftData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
initalize trajectory
Parameters
FlightTime flight time
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
AircraftData geometric data of aircraft
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented from Trajectory3Dof.
Reimplemented in RealSystemTrajectory.
Definition at line 23 of file Trajectory6DoF.cpp.
integrationTrajectory()
void Trajectory6Dof::integrationTrajectory (AirframeStruct & AirframeData, IMUStruct & IMUData, NavigationStruct & NavData)
integrate accelerations and calculate new flight states
Parameters
AirframeData flight statess
IMUData accelerations and rotatory rates
NavData structure that stores position and velocity
Definition at line 102 of file Trajectory6DoF.cpp.
Referenced by updateTrajectory().
log6DofData()
void Trajectory6Dof::log6DofData ()
log 6Dof Trajectory data
Definition at line 129 of file Trajectory6DoF.cpp.
Referenced by updateTrajectory().
updateTrajectory()
void Trajectory6Dof::updateTrajectory (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
calculate trajectory
Parameters
FlightTime flight time
AtmoData current atmospheric data
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented from Trajectory3Dof.
Reimplemented in RealSystemTrajectory.
Definition at line 55 of file Trajectory6DoF.cpp.
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory6DoF.h
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory6DoF.cpp