BaseAerodynamic Class Reference
#include <BaseAerodynamic.h>
Public Member Functions
BaseAerodynamic ()
constructor
~BaseAerodynamic ()
destructor
virtual void initAerodynamic (Float64 &FlightTime, AerodynamicStruct &AeroData, AircraftStruct &AircraftData)
The init function from the selected aerodynamic model is called by a pointer.
virtual void updateAerodynamic (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, ActuatorStruct &ActuatorData, IMUStruct &IMUData, NavigationStruct &NavData)
calculate aero forces and moments
virtual void LogAeroData ()
log aerodynamic data to text file
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
Base Aerodynamic class is the superclass for all aerodynamic models. Using pointer to base init and update function allows the user to extend the aerodynamic module with new models.
Definition at line 21 of file BaseAerodynamic.h.
Constructor & Destructor Documentation
BaseAerodynamic()
BaseAerodynamic::BaseAerodynamic ()
constructor
Definition at line 3 of file BaseAerodynamic.cpp.
 BaseAerodynamic()
BaseAerodynamic::~BaseAerodynamic ()
destructor
Definition at line 7 of file BaseAerodynamic.cpp.
Member Function Documentation
initAerodynamic()
void BaseAerodynamic::initAerodynamic (Float64 & FlightTime, AerodynamicStruct & AeroData, AircraftStruct & AircraftData) [virtual]
The init function from the selected aerodynamic model is called by a pointer.
Parameters
FlightTime flighttime
AeroData structure of aero data
AircraftData structure of aircraft data
Reimplemented in DATCOMAerodymamic.
Definition at line 25 of file BaseAerodynamic.cpp.
Referenced by Aerodynamics::initAerodynamic().
LogAeroData()
void BaseAerodynamic::LogAeroData () [virtual]
log aerodynamic data to text file
Reimplemented in DATCOMAerodymamic.
Definition at line 32 of file BaseAerodynamic.cpp.
Referenced by Aerodynamics::LogAeroData().
updateAerodynamic()
void BaseAerodynamic::updateAerodynamic (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, ActuatorStruct & ActuatorData, IMUStruct & IMUData, NavigationStruct & NavData) [virtual]
calculate aero forces and moments
Parameters
FlightTime Flight Time
AtmoData air density, speed of sound
AeroData structure of aero data
AirframeData structure of airframe data
ThrustData structure of thrust data
ActuatorData actuator angles
IMUData rotational rates
NavData Navigation data like velocity in NED system
Reimplemented in DATCOMAerodymamic.
Definition at line 11 of file BaseAerodynamic.cpp.
Referenced by Aerodynamics::updateAerodynamic().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Aerodynamic/BaseAerodynamic.h
C:/Users/janol/Desktop/Simulation_Stand230618/Aerodynamic/BaseAerodynamic.cpp