StateController Class Reference
#include <StateController.h>
Public Member Functions
StateController ()
construtor
~StateController ()
destrutor
void initStateController ()
read in and initalize state controller parameters
void updateStateController (Float64 FlightTime, AirframeStruct &AirframeData, AerodynamicStruct &AeroData, GuidanceStruct &GuidanceData, ActuatorStruct &ActuatorData, IMUStruct &IMUData, NavigationStruct &NavData)
calculate controlls depending on flight state
int sub2ind (const int row, const int column, const int rows, const int columns)
help functions to find index
int sign (Float64 val)
signum function
Detailed Description
Author
Jan Olucak
Date
10.04.2018
Version
1.0
StateController class simulates a state controller for flight states. Control variables are calculated with blending method.
Definition at line 21 of file StateController.h.
Constructor & Destructor Documentation
StateController()
StateController::StateController ()
construtor
Definition at line 3 of file StateController.cpp.
 StateController()
StateController::~StateController ()
destrutor
Definition at line 9 of file StateController.cpp.
Member Function Documentation
initStateController()
void StateController::initStateController ()
read in and initalize state controller parameters
1) get controller for every trim point in grid
2) initialise parameters
Definition at line 13 of file StateController.cpp.
Referenced by Autopilot::initAutopilot().
sign()
int StateController::sign (Float64 val)
signum function
Definition at line 207 of file StateController.cpp.
Referenced by updateStateController().
sub2ind()
int StateController::sub2ind (const int row, const int column, const int rows, const int columns)
help functions to find index
Parameters
row desired row
column desired column
rows total number of rows
columns total number of columns
Definition at line 202 of file StateController.cpp.
Referenced by updateStateController().
updateStateController()
void StateController::updateStateController (Float64 FlightTime, AirframeStruct & AirframeData, AerodynamicStruct & AeroData, GuidanceStruct & GuidanceData, ActuatorStruct & ActuatorData, IMUStruct & IMUData, NavigationStruct & NavData)
calculate controlls depending on flight state
Parameters
FlightTime flight time
AirframeData flight states
AeroData get angle of attack
GuidanceData control input
ActuatorData actuator angles
IMUData rotatory rates
NavData velocity
1) find neighbors in grid
2) get control input from guidance
3) calculate control variable for every grid neighbor
4) blending
Definition at line 93 of file StateController.cpp.
Referenced by Autopilot::updateAutopilot().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/StateController.h
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/StateController.cpp