Airframe Class Reference
#include <Airframe.h>
Public Member Functions
Airframe ()
constructor
~Airframe ()
destructor
void initAirframe (Float64 &FlightTime, AircraftStruct &AircraftData, AirframeStruct &AirframeData)
Airframe initialization Airframe and Aircraft Data are initialized. Parameters from Aircraft.dat are read in and stored in their specific structure.
void updateTranslational (AerodynamicStruct &AeroData, ThrustStruct &ThrustData, AirframeStruct &AirframeData)
translational equations of motion translational body accelerations are calculated
void updateRotatory (AerodynamicStruct &AeroData, ThrustStruct &ThrustData, AirframeStruct &AirframeData)
rotational equations of motion rotation body accelerations are calculated. Euler angle derivatives,too.
void initLogAirframeData (Float64 &FlightTime, AirframeStruct &AirframeData)
define output
void logAirframeData ()
log airframe data
Detailed Description
Definition at line 18 of file Airframe.h.
Constructor & Destructor Documentation
Airframe()
Airframe::Airframe ()
constructor
Definition at line 3 of file Airframe.cpp.
 Airframe()
Airframe::~Airframe ()
destructor
Definition at line 9 of file Airframe.cpp.
Member Function Documentation
initAirframe()
void Airframe::initAirframe (Float64 & FlightTime, AircraftStruct & AircraftData, AirframeStruct & AirframeData)
Airframe initialization Airframe and Aircraft Data are initialized. Parameters from Aircraft.dat are read in and stored in their specific structure.
1) read in geometric aircraft data (wingspan,...)
3) initialize airframe data
Definition at line 13 of file Airframe.cpp.
Referenced by Trajectory3Dof::initTrajectory3DoF().
initLogAirframeData()
void Airframe::initLogAirframeData (Float64 & FlightTime, AirframeStruct & AirframeData)
define output
Parameters
FlightTime flight time
AirframeData flight states
Definition at line 117 of file Airframe.cpp.
Referenced by initAirframe().
logAirframeData()
void Airframe::logAirframeData ()
log airframe data
Definition at line 126 of file Airframe.cpp.
Referenced by Trajectory3Dof::log3DofData().
updateRotatory()
void Airframe::updateRotatory (AerodynamicStruct & AeroData, ThrustStruct & ThrustData, AirframeStruct & AirframeData)
rotational equations of motion rotation body accelerations are calculated. Euler angle derivatives,too.
Parameters
AeroData Aerodynamic forces,moments and angles
ThrustData Thrust forces and moments
AirframeData store accelerations
1) get data from structs
2) calculate rotatory accelerations
3) calculate derivation of euler angles
Definition at line 86 of file Airframe.cpp.
Referenced by RealSystemTrajectory::updateTrajectory(), and Trajectory6Dof::updateTrajectory().
updateTranslational()
void Airframe::updateTranslational (AerodynamicStruct & AeroData, ThrustStruct & ThrustData, AirframeStruct & AirframeData)
translational equations of motion translational body accelerations are calculated
Parameters
AeroData Aerodynamic forces,moments and angles
ThrustData Thrust forces and moments
AirframeData store acceleration
1) get data from structs
2) calculate translational accelerations
Definition at line 64 of file Airframe.cpp.
Referenced by Trajectory3Dof::updateTrajectory3DoF().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Airframe/Airframe.h
C:/Users/janol/Desktop/Simulation_Stand230618/Airframe/Airframe.cpp