BaseIMU Class Reference
#include <BaseIMU.h>
Public Member Functions
BaseIMU ()
constructor
~BaseIMU ()
destructor
virtual void initIMU (IMUStruct &IMUData)
initialize IMU
virtual void updateIMU (Float64 FlightTime, AirframeStruct &AirframeData, IMUStruct &IMUData)
update IMU
virtual void logIMUData ()
log IMU data
Detailed Description
Author
Jan Olucak
Date
02.01.2018
Version
1.0
BaseIMU class is the superclass for all GPS models. Using pointer to base init and update function allows the user to extend the IMU module with new models.
Definition at line 18 of file BaseIMU.h.
Constructor & Destructor Documentation
BaseIMU()
BaseIMU::BaseIMU ()
constructor
Definition at line 3 of file BaseIMU.cpp.
 BaseIMU()
BaseIMU::~BaseIMU ()
destructor
Definition at line 7 of file BaseIMU.cpp.
Member Function Documentation
initIMU()
void BaseIMU::initIMU (IMUStruct & IMUData) [virtual]
initialize IMU
Reimplemented in flawlessIMU.
Definition at line 11 of file BaseIMU.cpp.
Referenced by IMU::initIMU().
logIMUData()
void BaseIMU::logIMUData () [virtual]
log IMU data
Reimplemented in flawlessIMU.
Definition at line 24 of file BaseIMU.cpp.
Referenced by IMU::logIMUData().
updateIMU()
void BaseIMU::updateIMU (Float64 FlightTime, AirframeStruct & AirframeData, IMUStruct & IMUData) [virtual]
update IMU
Parameters
FlightTime flight time
AirframeData structure of Airframe data
IMUData structure of IMU data
Reimplemented in flawlessIMU.
Definition at line 17 of file BaseIMU.cpp.
Referenced by IMU::updateIMU().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/IMU/BaseIMU.h
C:/Users/janol/Desktop/Simulation_Stand230618/IMU/BaseIMU.cpp