Trajectory3Dof Class Reference
#include <Trajectory3DoF.h>
Public Member Functions
Trajectory3Dof (SimDPreference &SimPref)
constructor
~Trajectory3Dof ()
destructor
virtual void initTrajectory (Float64 &FlightTime, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, AircraftStruct &AircraftData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
initalize trajectory
virtual void updateTrajectory (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
calculate trajectory
void initTrajectory3DoF (Float64 &FlightTime, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, AircraftStruct &AircraftData)
initalize 3 Dof trajectory
void updateTrajectory3DoF (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, ActuatorStruct &ActuatorData, IMUStruct &IMUData, NavigationStruct &NavData)
calculate 3 Dof trajectory
void log3DofData ()
log 3Dof Data (Aerodynamic Data, Thrust Data and translational acclerations)
Detailed Description
Definition at line 19 of file Trajectory3DoF.h.
Constructor & Destructor Documentation
Trajectory3Dof()
Trajectory3Dof::Trajectory3Dof (SimDPreference & SimPref)
constructor
Parameters
SimPref mode selection for trajectory
Definition at line 3 of file Trajectory3DoF.cpp.
 Trajectory3Dof()
Trajectory3Dof::~Trajectory3Dof ()
destructor
Definition at line 11 of file Trajectory3DoF.cpp.
Member Function Documentation
initTrajectory()
void Trajectory3Dof::initTrajectory (Float64 & FlightTime, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, AircraftStruct & AircraftData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
initalize trajectory
Parameters
FlightTime flight time
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
AircraftData geometric data of aircraft
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented from BaseTrajectory.
Reimplemented in RealSystemTrajectory, and Trajectory6Dof.
Definition at line 15 of file Trajectory3DoF.cpp.
initTrajectory3DoF()
void Trajectory3Dof::initTrajectory3DoF (Float64 & FlightTime, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, AircraftStruct & AircraftData)
initalize 3 Dof trajectory
Parameters
FlightTime flight time
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
AircraftData geometric data of aircraft
Definition at line 55 of file Trajectory3DoF.cpp.
Referenced by initTrajectory(), Trajectory6Dof::initTrajectory(), and RealSystemTrajectory::initTrajectory().
log3DofData()
void Trajectory3Dof::log3DofData ()
log 3Dof Data (Aerodynamic Data, Thrust Data and translational acclerations)
Definition at line 108 of file Trajectory3DoF.cpp.
Referenced by Trajectory6Dof::log6DofData(), and RealSystemTrajectory::logRealsystemTrajectory().
updateTrajectory()
void Trajectory3Dof::updateTrajectory (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
calculate trajectory
Parameters
FlightTime flight time
AtmoData current atmospheric data
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented from BaseTrajectory.
Reimplemented in Trajectory6Dof, and RealSystemTrajectory.
Definition at line 33 of file Trajectory3DoF.cpp.
updateTrajectory3DoF()
void Trajectory3Dof::updateTrajectory3DoF (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, ActuatorStruct & ActuatorData, IMUStruct & IMUData, NavigationStruct & NavData)
calculate 3 Dof trajectory
Parameters
FlightTime flight time
AtmoData current atmospheric data
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
ActuatorData real actuator angles
IMUData measured acceleration
NavData aircraft position, velocity
Definition at line 75 of file Trajectory3DoF.cpp.
Referenced by updateTrajectory(), RealSystemTrajectory::updateTrajectory(), and Trajectory6Dof::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory3DoF.h
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory3DoF.cpp