DataLogger Class Reference
#include <DataLogger.h>
Public Member Functions
DataLogger (std::string Path, int Width, std::string Delimiter)
constructor
~DataLogger ()
Destructor.
void add (std::string Header, double &Var)
defines variable which is stored in outputfile (double)
void add (std::string Header, int &Var)
defines variable which is stored in outputfile (integer)
void print ()
writes defined variable to an outputfile
void printHeader ()
defines header of specific variable
std::string to_string2 (Float64 value)
Detailed Description
Definition at line 25 of file DataLogger.h.
Constructor & Destructor Documentation
DataLogger()
DataLogger::DataLogger (std::string Path, int Width, std::string Delimiter)
constructor
Definition at line 4 of file DataLogger.cpp.
 DataLogger()
DataLogger::~DataLogger ()
Destructor.
Definition at line 18 of file DataLogger.cpp.
Member Function Documentation
add() [1/2]
void DataLogger::add (std::string Header, double & Var)
defines variable which is stored in outputfile (double)
Definition at line 23 of file DataLogger.cpp.
Referenced by AerodynamicTest(), AtmosphereTest(), GuidanceTest(), Trajectory6Dof::initLog6Dof(), flawlessActuator::initLogActuatorData(), DATCOMAerodymamic::initLogAeroData(), Airframe::initLogAirframeData(), ThrustAnalytical::initLogEngineData(), accTable::initLogGuidance(), flawlessIMU::initlogIMUData(), and flawlessNavigation::initlogNavigationData().
add() [2/2]
void DataLogger::add (std::string Header, int & Var)
defines variable which is stored in outputfile (integer)
Definition at line 30 of file DataLogger.cpp.
print()
void DataLogger::print ()
writes defined variable to an outputfile
Definition at line 38 of file DataLogger.cpp.
Referenced by AerodynamicTest(), AtmosphereTest(), Trajectory6Dof::log6DofData(), flawlessActuator::LogActuatorData(), DATCOMAerodymamic::LogAeroData(), Airframe::logAirframeData(), ThrustAnalytical::logEngineData(), accTable::logGuidanceData(), flawlessIMU::logIMUData(), and flawlessNavigation::logNavigationData().
printHeader()
void DataLogger::printHeader ()
defines header of specific variable
Definition at line 60 of file DataLogger.cpp.
Referenced by AerodynamicTest(), AtmosphereTest(), GuidanceTest(), Trajectory6Dof::initLog6Dof(), flawlessActuator::initLogActuatorData(), DATCOMAerodymamic::initLogAeroData(), Airframe::initLogAirframeData(), ThrustAnalytical::initLogEngineData(), accTable::initLogGuidance(), flawlessIMU::initlogIMUData(), and flawlessNavigation::initlogNavigationData().
to_string2()
std::string DataLogger::to_string2 (Float64 value)
Definition at line 78 of file DataLogger.cpp.
Referenced by print().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/DataLogger.h
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/DataLogger.cpp