Actuator Class Reference
#include <Actuator.h>
Public Member Functions
Actuator (SimDPreference &SimPref)
constructor
~Actuator ()
destructor
void initActuator (Float64 &FlightTime, AirframeStruct &AirframeData, ActuatorStruct &ActuatorData)
initialize selected actuator model
void selectActuatorType (int type)
switch function to select desired model
void updateActuator (Float64 FlightTime, AirframeStruct &AirframeData, ActuatorStruct &ActuatorData)
update actuator model
void logActuator ()
data logger for actuator data
Detailed Description
Definition at line 18 of file Actuator.h.
Constructor & Destructor Documentation
Actuator()
Actuator::Actuator (SimDPreference & SimPref)
constructor
Parameters
SimPref Selected Actuator model
Definition at line 3 of file Actuator.cpp.
 Actuator()
Actuator::~Actuator ()
destructor
Definition at line 8 of file Actuator.cpp.
Member Function Documentation
initActuator()
void Actuator::initActuator (Float64 & FlightTime, AirframeStruct & AirframeData, ActuatorStruct & ActuatorData)
initialize selected actuator model
Parameters
FlightTime Flight time
AirframeData coammanded actuator angles from autopilot
ActuatorData real Actuator angles
Definition at line 12 of file Actuator.cpp.
Referenced by RealSystemTrajectory::initTrajectory().
logActuator()
void Actuator::logActuator ()
data logger for actuator data
Definition at line 42 of file Actuator.cpp.
Referenced by RealSystemTrajectory::logRealsystemTrajectory().
selectActuatorType()
void Actuator::selectActuatorType (int type)
switch function to select desired model
Parameters
type selected model (as integer value9
Definition at line 21 of file Actuator.cpp.
Referenced by Actuator().
updateActuator()
void Actuator::updateActuator (Float64 FlightTime, AirframeStruct & AirframeData, ActuatorStruct & ActuatorData)
update actuator model
Parameters
FlightTime Flight time
AirframeData coammanded actuator angles from autopilot
ActuatorData real Actuator angles
Definition at line 32 of file Actuator.cpp.
Referenced by RealSystemTrajectory::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Actuator/Actuator.h
C:/Users/janol/Desktop/Simulation_Stand230618/Actuator/Actuator.cpp