FindNeighbor Class Reference
#include <FindNeighbor.h>
Public Member Functions
FindNeighbor ()
constructor
~FindNeighbor ()
destructor
void initFindNeighbor ()
trim states are read in
std::tuple< Eigen::Vector4d, Eigen::MatrixXd > BlendingParameters (NavigationStruct &NavData)
blending parameters for gain scheduing are calculated
Eigen::MatrixXd combineVec (Eigen::Vector2d &Alt, Eigen::Vector2d &Vel)
help function to combine vectors for gain scheduling
int sub2ind (const int row, const int column, const int rows, const int columns)
help functions to find index
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
FindNeighbor class calculates parameters for gain scheduling.
Definition at line 21 of file FindNeighbor.h.
Constructor & Destructor Documentation
FindNeighbor()
FindNeighbor::FindNeighbor ()
constructor
Definition at line 3 of file FindNeighbor.cpp.
 FindNeighbor()
FindNeighbor::~FindNeighbor ()
destructor
Definition at line 7 of file FindNeighbor.cpp.
Member Function Documentation
BlendingParameters()
std::tuple< Eigen::Vector4d, Eigen::MatrixXd > FindNeighbor::BlendingParameters (NavigationStruct & NavData)
blending parameters for gain scheduing are calculated
Parameters
NavData structure of airframe parameters
Definition at line 36 of file FindNeighbor.cpp.
Referenced by StateController::updateStateController().
combineVec()
Eigen::MatrixXd FindNeighbor::combineVec (Eigen::Vector2d & Alt, Eigen::Vector2d & Vel)
help function to combine vectors for gain scheduling
Parameters
Alt Vector of altitude
Vel Vector of velocity
Definition at line 82 of file FindNeighbor.cpp.
Referenced by BlendingParameters().
initFindNeighbor()
void FindNeighbor::initFindNeighbor ()
trim states are read in
Definition at line 12 of file FindNeighbor.cpp.
Referenced by StateController::initStateController().
sub2ind()
int FindNeighbor::sub2ind (const int row, const int column, const int rows, const int columns)
help functions to find index
Parameters
row desired row
column desired column
rows total number of rows
columns total number of columns
Definition at line 91 of file FindNeighbor.cpp.
Referenced by BlendingParameters().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/FindNeighbor.h
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/FindNeighbor.cpp