Aerodynamics Class Reference
#include <Aerodynamic.h>
Public Member Functions
Aerodynamics (SimDPreference &SimPref)
constructor
~Aerodynamics ()
destructor
void selectAerodynamicType (int type)
set pointer to desired class
void initAerodynamic (Float64 &FlightTime, AerodynamicStruct &AeroData, AircraftStruct &AircraftData)
initialize aerodynamic paramters
void updateAerodynamic (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, ActuatorStruct &ActuatorData, IMUStruct &IMUData, NavigationStruct &NavData)
calculate aero forces and moments
void LogAeroData ()
log aerodynamic data to text file
Detailed Description
Definition at line 22 of file Aerodynamic.h.
Constructor & Destructor Documentation
Aerodynamics()
Aerodynamics::Aerodynamics (SimDPreference & SimPref)
constructor
Parameters
SimPref structure of model selctions
Definition at line 3 of file Aerodynamic.cpp.
 Aerodynamics()
Aerodynamics::~Aerodynamics ()
destructor
Definition at line 9 of file Aerodynamic.cpp.
Member Function Documentation
initAerodynamic()
void Aerodynamics::initAerodynamic (Float64 & FlightTime, AerodynamicStruct & AeroData, AircraftStruct & AircraftData)
initialize aerodynamic paramters
Parameters
FlightTime flighttime
AeroData structure of aero data
AircraftData structure of aircraft data
Definition at line 24 of file Aerodynamic.cpp.
Referenced by AerodynamicTest(), GuidanceTest(), and Trajectory3Dof::initTrajectory3DoF().
LogAeroData()
void Aerodynamics::LogAeroData ()
log aerodynamic data to text file
Definition at line 53 of file Aerodynamic.cpp.
Referenced by Trajectory3Dof::log3DofData().
selectAerodynamicType()
void Aerodynamics::selectAerodynamicType (int type)
set pointer to desired class
Parameters
type Aerodynamic Model Selection
Definition at line 13 of file Aerodynamic.cpp.
Referenced by Aerodynamics().
updateAerodynamic()
void Aerodynamics::updateAerodynamic (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, ActuatorStruct & ActuatorData, IMUStruct & IMUData, NavigationStruct & NavData)
calculate aero forces and moments
Parameters
FlightTime Flight Time
AtmoData air density, speed of sound
AeroData structure of aero data
AirframeData structure of airframe data
ThrustData structure of thrust data
ActuatorData actuator angles
IMUData rotational rates
NavData Navigation data like velocity in NED system
Definition at line 33 of file Aerodynamic.cpp.
Referenced by AerodynamicTest(), GuidanceTest(), and Trajectory3Dof::updateTrajectory3DoF().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Aerodynamic/Aerodynamic.h
C:/Users/janol/Desktop/Simulation_Stand230618/Aerodynamic/Aerodynamic.cpp