Navigation Class Reference
#include <Navigation.h>
Public Member Functions
Navigation (SimDPreference &SimPref)
constructor
~Navigation ()
destructor
void selectNavigation (int Type)
set pointer to desired class
void initNavigation (Float64 &FlightTime, NavigationStruct &NavData, IMUStruct &IMUData)
call to desired init-function
void updateNavigation (Float64 FlightTime, NavigationStruct &NavData, AirframeStruct &AirframeData, IMUStruct &IMUData)
call to desired update function
void logNavigationData ()
data logger for navigation data
Detailed Description
Definition at line 20 of file Navigation.h.
Constructor & Destructor Documentation
Navigation()
Navigation::Navigation (SimDPreference & SimPref)
constructor
Parameters
SimPref structure of model selctions
Definition at line 3 of file Navigation.cpp.
 Navigation()
Navigation::~Navigation ()
destructor
Definition at line 9 of file Navigation.cpp.
Member Function Documentation
initNavigation()
void Navigation::initNavigation (Float64 & FlightTime, NavigationStruct & NavData, IMUStruct & IMUData)
call to desired init-function
Definition at line 24 of file Navigation.cpp.
Referenced by RealSystemTrajectory::initTrajectory().
logNavigationData()
void Navigation::logNavigationData ()
data logger for navigation data
Definition at line 44 of file Navigation.cpp.
Referenced by RealSystemTrajectory::logRealsystemTrajectory().
selectNavigation()
void Navigation::selectNavigation (int Type)
set pointer to desired class
Parameters
Type navigation Model Selection
Definition at line 13 of file Navigation.cpp.
Referenced by Navigation().
updateNavigation()
void Navigation::updateNavigation (Float64 FlightTime, NavigationStruct & NavData, AirframeStruct & AirframeData, IMUStruct & IMUData)
call to desired update function
Parameters
FlightTime flighttime
NavData structure of navigation data
AirframeData flight states
IMUData structure of acceleratiosn and rotatory rates
Definition at line 33 of file Navigation.cpp.
Referenced by RealSystemTrajectory::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Navigation/Navigation.h
C:/Users/janol/Desktop/Simulation_Stand230618/Navigation/Navigation.cpp