Moduletest
Functions
void AtmosphereTest ()
The atmospheric model is tested. Hence altitude is increased up to 10000m. Atmospheric data is stored and plotted in Matlab. The plots are compared to characteritic trends.
void AerodynamicTest (SimDPreference &SimPref)
Datcom aerodynamic is tested. Therefor a windtunnel is simulate. Within loops Angle of attack, elevator angle and mach are varied. Characterisitcs (e.g. drag polar) are calculated for several flight states. Only longitudinal aerodynamic is tested.
void GuidanceTest (SimDPreference &SimPref)
void TrajectoryTest (SimDPreference &SimPref)
int main ()
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
ModuleTest.cpp cotains module tests for several modules. Some modules need a complete simulation to be tested
Function Documentation
AerodynamicTest()
void AerodynamicTest (SimDPreference & SimPref)
Datcom aerodynamic is tested. Therefor a windtunnel is simulate. Within loops Angle of attack, elevator angle and mach are varied. Characterisitcs (e.g. drag polar) are calculated for several flight states. Only longitudinal aerodynamic is tested.
1) Initialization of models and data
2) aircraft characterisitcs and simulation data are read in
3) Definition of Output
4) 3 loops simulate a wind tunnel with varying flight states
Definition at line 73 of file ModuleTest.cpp.
Referenced by main().
AtmosphereTest()
void AtmosphereTest ()
The atmospheric model is tested. Hence altitude is increased up to 10000m. Atmospheric data is stored and plotted in Matlab. The plots are compared to characteritic trends.
1) Initialization of models and data
2) Loop increases altitude; data is stored to outputfile
Definition at line 38 of file ModuleTest.cpp.
Referenced by main().
GuidanceTest()
void GuidanceTest (SimDPreference & SimPref)
Definition at line 196 of file ModuleTest.cpp.
Referenced by main().
main()
int main ()
Definition at line 373 of file ModuleTest.cpp.
TrajectoryTest()
void TrajectoryTest (SimDPreference & SimPref)
Definition at line 276 of file ModuleTest.cpp.