BaseTrajectory Class Reference
#include <BaseTrajectory.h>
Public Member Functions
BaseTrajectory ()
constructor
~BaseTrajectory ()
destructor
virtual void initTrajectory (Float64 &FlightTime, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, AircraftStruct &AircraftData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
initalize trajectory
virtual void updateTrajectory (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
calculate trajectory
virtual void logTraj ()
log trajectory data
Detailed Description
Author
Jan Olucak
Date
28.11.2017
Version
1.0
BaseTrajectory is the superclass for all trajectory classes.
Definition at line 14 of file BaseTrajectory.h.
Constructor & Destructor Documentation
BaseTrajectory()
BaseTrajectory::BaseTrajectory ()
constructor
Definition at line 3 of file BaseTrajectory.cpp.
 BaseTrajectory()
BaseTrajectory::~BaseTrajectory ()
destructor
Definition at line 7 of file BaseTrajectory.cpp.
Member Function Documentation
initTrajectory()
void BaseTrajectory::initTrajectory (Float64 & FlightTime, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, AircraftStruct & AircraftData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
initalize trajectory
Parameters
FlightTime flight time
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
AircraftData geometric data of aircraft
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented in RealSystemTrajectory, Trajectory6Dof, and Trajectory3Dof.
Definition at line 11 of file BaseTrajectory.cpp.
Referenced by Trajectory::initTrajectory().
logTraj()
void BaseTrajectory::logTraj () [virtual]
log trajectory data
Definition at line 37 of file BaseTrajectory.cpp.
Referenced by Trajectory::logTraj().
updateTrajectory()
void BaseTrajectory::updateTrajectory (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData) [virtual]
calculate trajectory
Parameters
FlightTime flight time
AtmoData current atmospheric data
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Reimplemented in Trajectory6Dof, RealSystemTrajectory, and Trajectory3Dof.
Definition at line 24 of file BaseTrajectory.cpp.
Referenced by Trajectory::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/BaseTrajectory.h
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/BaseTrajectory.cpp