Atmopshere Class Reference
#include <Atmosphere.h>
Public Member Functions
Atmopshere ()
constructor
~Atmopshere ()
destructor
void initAtmosphere ()
initialize atmospheric paramters
void updateAtmosphere (Float64 &Altitude, AtmosphereStruct &AtmoData)
calculates atmospheric data depending on altitude
Detailed Description
Definition at line 20 of file Atmosphere.h.
Constructor & Destructor Documentation
Atmopshere()
Atmopshere::Atmopshere ()
constructor
Definition at line 3 of file Atmosphere.cpp.
 Atmopshere()
Atmopshere::~Atmopshere ()
destructor
Definition at line 7 of file Atmosphere.cpp.
Member Function Documentation
initAtmosphere()
void Atmopshere::initAtmosphere ()
initialize atmospheric paramters
Definition at line 11 of file Atmosphere.cpp.
Referenced by AtmosphereTest(), Aircraft::simulateAircraft(), and TrajectoryTest().
updateAtmosphere()
void Atmopshere::updateAtmosphere (Float64 & Altitude, AtmosphereStruct & AtmoData)
calculates atmospheric data depending on altitude
Parameters
Altitude current altitude
AtmoData store air density, speed of sound, temperature, pressure
US Standard atmosphere
Definition at line 22 of file Atmosphere.cpp.
Referenced by AtmosphereTest(), Aircraft::simulateAircraft(), and TrajectoryTest().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Atmosphere/Atmosphere.h
C:/Users/janol/Desktop/Simulation_Stand230618/Atmosphere/Atmosphere.cpp