BaseThrust Class Reference
#include <BaseThrust.h>
Public Member Functions
BaseThrust ()
constructor
~BaseThrust ()
destructor
virtual void updateThrust (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, ActuatorStruct &ActuatorData)
virtual void initThrust (Float64 &FlightTime, ThrustStruct &ThrustData, AircraftStruct &AircraftData)
virtual void logEngineData ()
log engine data
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
Base Thrust class is the superclass for all engine models. Using pointer to base init and update function allows the user to extend the engine module with new engine models.
Definition at line 22 of file BaseThrust.h.
Constructor & Destructor Documentation
BaseThrust()
BaseThrust::BaseThrust ()
constructor
Definition at line 3 of file BaseThrust.cpp.
 BaseThrust()
BaseThrust::~BaseThrust ()
destructor
Definition at line 7 of file BaseThrust.cpp.
Member Function Documentation
initThrust()
void BaseThrust::initThrust (Float64 & FlightTime, ThrustStruct & ThrustData, AircraftStruct & AircraftData) [virtual]
The init function from the selected engine is called by a pointer.
Parameters
FlightTime flight time
ThrustData structure of engine data
AircraftData structure of aircraft data
Reimplemented in ThrustAnalytical.
Definition at line 11 of file BaseThrust.cpp.
Referenced by Engine::initEngine().
logEngineData()
void BaseThrust::logEngineData () [virtual]
log engine data
Reimplemented in ThrustAnalytical.
Definition at line 18 of file BaseThrust.cpp.
Referenced by Engine::logEngineData().
updateThrust()
void BaseThrust::updateThrust (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, ActuatorStruct & ActuatorData) [virtual]
The update function from the selected engine is called by a pointer.
Parameters
FlightTime flight time
AtmoData get current atmospheric data
AeroData get mach number
AirframeData get current throttle stick position
ThrustData store thrust data
ActuatorData get thrust stick position
Reimplemented in ThrustAnalytical.
Definition at line 23 of file BaseThrust.cpp.
Referenced by Engine::updateEngine().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Engine/BaseThrust.h
C:/Users/janol/Desktop/Simulation_Stand230618/Engine/BaseThrust.cpp