IMU Class Reference
#include <IMU.h>
Public Member Functions
IMU (SimDPreference &SimPref)
constructor
~IMU ()
destructor
void selectIMU (int Type)
set pointer to desired class
void initIMU (IMUStruct &IMUData)
call to desired init-function
void updateIMU (Float64 FlightTime, AirframeStruct &AirframeData, IMUStruct &IMUData)
call to desired update function
void logIMUData ()
log IMU data
Detailed Description
Definition at line 20 of file IMU.h.
Constructor & Destructor Documentation
IMU()
IMU::IMU (SimDPreference & SimPref)
constructor
Parameters
SimPref structure of model selctions
Definition at line 3 of file IMU.cpp.
 IMU()
IMU::~IMU ()
destructor
Definition at line 8 of file IMU.cpp.
Member Function Documentation
initIMU()
void IMU::initIMU (IMUStruct & IMUData)
call to desired init-function
Definition at line 22 of file IMU.cpp.
Referenced by RealSystemTrajectory::initTrajectory().
logIMUData()
void IMU::logIMUData ()
log IMU data
Definition at line 36 of file IMU.cpp.
Referenced by RealSystemTrajectory::logRealsystemTrajectory().
selectIMU()
void IMU::selectIMU (int Type)
set pointer to desired class
Parameters
Type Aerodynamic Model Selection
Definition at line 12 of file IMU.cpp.
Referenced by IMU().
updateIMU()
void IMU::updateIMU (Float64 FlightTime, AirframeStruct & AirframeData, IMUStruct & IMUData)
call to desired update function
Parameters
FlightTime flighttime
AirframeData structure of airframe data
IMUData structure of IMU data
Definition at line 27 of file IMU.cpp.
Referenced by RealSystemTrajectory::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/IMU/IMU.h
C:/Users/janol/Desktop/Simulation_Stand230618/IMU/IMU.cpp