GPS Class Reference
#include <GPS.h>
Public Member Functions
GPS (SimDPreference &SimPref)
constructor
~GPS ()
destructor
void selectGPS (int Type)
set pointer to desired class
void initGPS ()
call to desired init-function
void updateGPS (Float64 FlightTime, NavigationStruct &NavData, AirframeStruct &AirframeData)
call to desired update function
void logGPSData ()
log GPS data
Detailed Description
Definition at line 20 of file GPS.h.
Constructor & Destructor Documentation
GPS()
GPS::GPS (SimDPreference & SimPref)
constructor
Parameters
SimPref structure of model selctions
Definition at line 3 of file GPS.cpp.
 GPS()
GPS::~GPS ()
destructor
Definition at line 8 of file GPS.cpp.
Member Function Documentation
initGPS()
void GPS::initGPS ()
call to desired init-function
Definition at line 22 of file GPS.cpp.
Referenced by RealSystemTrajectory::initTrajectory().
logGPSData()
void GPS::logGPSData ()
log GPS data
Definition at line 36 of file GPS.cpp.
selectGPS()
void GPS::selectGPS (int Type)
set pointer to desired class
Parameters
Type Aerodynamic Model Selection
Definition at line 12 of file GPS.cpp.
Referenced by GPS().
updateGPS()
void GPS::updateGPS (Float64 FlightTime, NavigationStruct & NavData, AirframeStruct & AirframeData)
call to desired update function
Parameters
FlightTime flighttime
NavData structure of navigation data
AirframeData structure of flight states
Definition at line 27 of file GPS.cpp.
Referenced by RealSystemTrajectory::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/GPS/GPS.h
C:/Users/janol/Desktop/Simulation_Stand230618/GPS/GPS.cpp