Engine Class Reference
#include <Engine.h>
Public Member Functions
Engine (SimDPreference &SimPref)
constructor
~Engine ()
destructor
void selectEngineType (int type)
select Engine Type depending on input file
void initEngine (Float64 &FlightTime, ThrustStruct &ThrustData, AircraftStruct &AircraftData)
initilization of engine specific data
void updateEngine (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, ActuatorStruct &ActuatorData)
void logEngineData ()
log engine data
Detailed Description
Definition at line 19 of file Engine.h.
Constructor & Destructor Documentation
Engine()
Engine::Engine (SimDPreference & SimPref)
constructor
Parameters
SimPref mode selection for engine
Definition at line 3 of file Engine.cpp.
 Engine()
Engine::~Engine ()
destructor
Definition at line 8 of file Engine.cpp.
Member Function Documentation
initEngine()
void Engine::initEngine (Float64 & FlightTime, ThrustStruct & ThrustData, AircraftStruct & AircraftData)
initilization of engine specific data
Parameters
FlightTime flight time
ThrustData structure of engine data
AircraftData structure of aircraft data
Definition at line 23 of file Engine.cpp.
Referenced by Trajectory3Dof::initTrajectory3DoF().
logEngineData()
void Engine::logEngineData ()
log engine data
Definition at line 48 of file Engine.cpp.
Referenced by Trajectory3Dof::log3DofData().
selectEngineType()
void Engine::selectEngineType (int type)
select Engine Type depending on input file
Parameters
type specific integer to select desired engine
Definition at line 12 of file Engine.cpp.
Referenced by Engine().
updateEngine()
void Engine::updateEngine (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, ActuatorStruct & ActuatorData)
The update function from the selected engine is called by a pointer.
Parameters
FlightTime flight time
AtmoData get current atmospheric data
AeroData get mach number
AirframeData get current throttle stick position
ThrustData store thrust data
ActuatorData get thrust stick position
Definition at line 33 of file Engine.cpp.
Referenced by Trajectory3Dof::updateTrajectory3DoF().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Engine/Engine.h
C:/Users/janol/Desktop/Simulation_Stand230618/Engine/Engine.cpp