BaseNavigation Class Reference
#include <BaseNavigation.h>
Public Member Functions
BaseNavigation ()
constructor
~BaseNavigation ()
destructor
virtual void initNavigation (Float64 &FlightTime, NavigationStruct &NavData, IMUStruct &IMUData)
initialize navigation
virtual void updateNavigation (Float64 FlightTime, NavigationStruct &NavData, AirframeStruct &AirframeData, IMUStruct &IMUData)
call to desired update function
virtual void logNavigationData ()
data logger for navigation data
Detailed Description
Author
Jan Olucak
Date
02.01.2018
Version
1.0
BaseNavigation class is the superclass for all Navigation models. Using pointer to base init and update function allows the user to extend the Navigation module with new models.
Definition at line 18 of file BaseNavigation.h.
Constructor & Destructor Documentation
BaseNavigation()
BaseNavigation::BaseNavigation ()
constructor
Definition at line 3 of file BaseNavigation.cpp.
 BaseNavigation()
BaseNavigation::~BaseNavigation ()
destructor
Definition at line 7 of file BaseNavigation.cpp.
Member Function Documentation
initNavigation()
void BaseNavigation::initNavigation (Float64 & FlightTime, NavigationStruct & NavData, IMUStruct & IMUData) [virtual]
initialize navigation
Reimplemented in flawlessNavigation.
Definition at line 11 of file BaseNavigation.cpp.
Referenced by Navigation::initNavigation().
logNavigationData()
void BaseNavigation::logNavigationData () [virtual]
data logger for navigation data
Reimplemented in flawlessNavigation.
Definition at line 27 of file BaseNavigation.cpp.
Referenced by Navigation::logNavigationData().
updateNavigation()
void BaseNavigation::updateNavigation (Float64 FlightTime, NavigationStruct & NavData, AirframeStruct & AirframeData, IMUStruct & IMUData) [virtual]
call to desired update function
Parameters
FlightTime flighttime
NavData structure of navigation data
AirframeData structure of flight states
IMUData structures with accelerations and rotatory rates
Reimplemented in flawlessNavigation.
Definition at line 19 of file BaseNavigation.cpp.
Referenced by Navigation::updateNavigation().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Navigation/BaseNavigation.h
C:/Users/janol/Desktop/Simulation_Stand230618/Navigation/BaseNavigation.cpp