BaseGuidance Class Reference
#include <BaseGuidance.h>
Public Member Functions
BaseGuidance ()
constructor
~BaseGuidance ()
destructor
virtual void initGuidance (Float64 &FlightTime, GuidanceStruct &GuidanceData, AircraftStruct &AircraftData)
accTables are read in and stored in row vectors
virtual void updateGuidance (Float64 FlightTime, AerodynamicStruct &AeroData, ThrustStruct &ThrustData, AirframeStruct &AirframeData, GuidanceStruct &GuidanceData)
calculate commands for flight path
virtual void initLogGuidance (Float64 FlightTime, GuidanceStruct &GuidanceData)
define output for guidance data
virtual void logGuidanceData ()
log guidance data
Detailed Description
Author
Jan Olucak
Date
23.12.2017
Version
1.0
BaseGuidance is the superclass for all guidance models
Definition at line 18 of file BaseGuidance.h.
Constructor & Destructor Documentation
BaseGuidance()
BaseGuidance::BaseGuidance ()
constructor
Definition at line 3 of file BaseGuidance.cpp.
 BaseGuidance()
BaseGuidance::~BaseGuidance ()
destructor
Definition at line 7 of file BaseGuidance.cpp.
Member Function Documentation
initGuidance()
void BaseGuidance::initGuidance (Float64 & FlightTime, GuidanceStruct & GuidanceData, AircraftStruct & AircraftData) [virtual]
accTables are read in and stored in row vectors
Parameters
FlightTime flight time
GuidanceData structure of Guidance data
AircraftData specific airfraft data
Reimplemented in accTable.
Definition at line 11 of file BaseGuidance.cpp.
Referenced by Guidance::initGuidance().
initLogGuidance()
void BaseGuidance::initLogGuidance (Float64 FlightTime, GuidanceStruct & GuidanceData) [virtual]
define output for guidance data
Parameters
FlightTime flight time
GuidanceData structure of guidance data
Definition at line 25 of file BaseGuidance.cpp.
logGuidanceData()
void BaseGuidance::logGuidanceData () [virtual]
log guidance data
Reimplemented in accTable.
Definition at line 30 of file BaseGuidance.cpp.
Referenced by Guidance::logGuidanceData().
updateGuidance()
void BaseGuidance::updateGuidance (Float64 FlightTime, AerodynamicStruct & AeroData, ThrustStruct & ThrustData, AirframeStruct & AirframeData, GuidanceStruct & GuidanceData) [virtual]
calculate commands for flight path
Parameters
FlightTime flight time
AeroData structure of aero data
ThrustData structure of thrust data
AirframeData structure of airframe data
GuidanceData structure of guidance data
Reimplemented in accTable.
Definition at line 16 of file BaseGuidance.cpp.
Referenced by Guidance::updateGuidance().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Guidance/BaseGuidance.h
C:/Users/janol/Desktop/Simulation_Stand230618/Guidance/BaseGuidance.cpp