readInData Class Reference
#include <readInData.h>
Public Member Functions
readInData ()
constructor
~readInData ()
destructor
Float64 readInParameter (std::string CodeWord, std::string Filename)
read in a specific value from a file
MatrixXd readInTable (std::string FileName)
read in tables from input file
VectorXd readInVector (std::string FileName)
read in vector from input file
void setPath (std::string Pathname)
defines a relative path directory of input file
Detailed Description
Definition at line 29 of file readInData.h.
Constructor & Destructor Documentation
readInData()
readInData::readInData ()
constructor
Definition at line 2 of file readInData.cpp.
 readInData()
readInData::~readInData ()
destructor
Definition at line 7 of file readInData.cpp.
Member Function Documentation
readInParameter()
Float64 readInData::readInParameter (std::string CodeWord, std::string Filename)
read in a specific value from a file
Parameters
CodeWord specific name of a parameter
Filename Name of specific file
Definition at line 11 of file readInData.cpp.
Referenced by AerodynamicTest(), GuidanceTest(), Airframe::initAirframe(), ThrustAnalytical::initThrust(), main(), and UnitTest1::TEST_CLASS().
readInTable()
MatrixXd readInData::readInTable (std::string FileName)
read in tables from input file
Parameters
FileName Name of specific file
Definition at line 59 of file readInData.cpp.
Referenced by UnitTest1::TEST_CLASS().
readInVector()
VectorXd readInData::readInVector (std::string FileName)
read in vector from input file
Parameters
FileName Name of specific file
Definition at line 125 of file readInData.cpp.
Referenced by AerodynamicTest(), and UnitTest1::TEST_CLASS().
setPath()
void readInData::setPath (std::string Pathname)
defines a relative path directory of input file
Parameters
Pathname relative path of data file directory
Definition at line 173 of file readInData.cpp.
Referenced by AerodynamicTest(), DATCOMAerodymamic::initAerodynamic(), and UnitTest1::TEST_CLASS().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/readInData.h
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/readInData.cpp