Guidance Class Reference
#include <Guidance.h>
Public Member Functions
Guidance (SimDPreference &SimPref)
constructor
~Guidance ()
destructor
void selectGuidance (int Type)
set pointer to desired class
void initGuidance (Float64 &FlightTime, GuidanceStruct &GuidanceData, AircraftStruct &AircraftData)
initialize desired Guidance Model
void updateGuidance (Float64 FlightTime, AerodynamicStruct &AeroData, ThrustStruct &ThrustData, AirframeStruct &AirframeData, GuidanceStruct &GuidanceData)
calculate commands for flight path
void logGuidanceData ()
log guidance data
Detailed Description
Definition at line 20 of file Guidance.h.
Constructor & Destructor Documentation
Guidance()
Guidance::Guidance (SimDPreference & SimPref)
constructor
Parameters
SimPref Structure with model selection
Definition at line 3 of file Guidance.cpp.
 Guidance()
Guidance::~Guidance ()
destructor
Definition at line 9 of file Guidance.cpp.
Member Function Documentation
initGuidance()
void Guidance::initGuidance (Float64 & FlightTime, GuidanceStruct & GuidanceData, AircraftStruct & AircraftData)
initialize desired Guidance Model
Parameters
FlightTime flight time
GuidanceData structure of Guidance data
AircraftData specific airfraft data
Definition at line 25 of file Guidance.cpp.
Referenced by GuidanceTest(), Trajectory6Dof::initTrajectory(), and RealSystemTrajectory::initTrajectory().
logGuidanceData()
void Guidance::logGuidanceData ()
log guidance data
Definition at line 48 of file Guidance.cpp.
Referenced by GuidanceTest(), Trajectory6Dof::log6DofData(), and RealSystemTrajectory::logRealsystemTrajectory().
selectGuidance()
void Guidance::selectGuidance (int Type)
set pointer to desired class
Parameters
Type Aerodynamic Model Selection
Definition at line 13 of file Guidance.cpp.
Referenced by Guidance().
updateGuidance()
void Guidance::updateGuidance (Float64 FlightTime, AerodynamicStruct & AeroData, ThrustStruct & ThrustData, AirframeStruct & AirframeData, GuidanceStruct & GuidanceData)
calculate commands for flight path
Parameters
FlightTime flight time
AeroData structure of aero data
ThrustData structure of thrust data
AirframeData structure of airframe data
GuidanceData structure of guidance data
Definition at line 35 of file Guidance.cpp.
Referenced by GuidanceTest(), RealSystemTrajectory::updateTrajectory(), and Trajectory6Dof::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Guidance/Guidance.h
C:/Users/janol/Desktop/Simulation_Stand230618/Guidance/Guidance.cpp