Autopilot Class Reference
#include <Autopilot.h>
Public Member Functions
Autopilot ()
constructor
~Autopilot ()
destructor
void initAutopilot ()
initialize autopilot
void updateAutopilot (Float64 FlightTime, AirframeStruct &AirframeData, AerodynamicStruct &AeroData, GuidanceStruct &GuidanceData, ActuatorStruct &ActuatorData, IMUStruct &IMUData, NavigationStruct &NavData)
calculate controlls
Detailed Description
Definition at line 18 of file Autopilot.h.
Constructor & Destructor Documentation
Autopilot()
Autopilot::Autopilot ()
constructor
Definition at line 3 of file Autopilot.cpp.
 Autopilot()
Autopilot::~Autopilot ()
destructor
Definition at line 8 of file Autopilot.cpp.
Member Function Documentation
initAutopilot()
void Autopilot::initAutopilot ()
initialize autopilot
Definition at line 13 of file Autopilot.cpp.
Referenced by RealSystemTrajectory::initTrajectory(), and Trajectory6Dof::initTrajectory().
updateAutopilot()
void Autopilot::updateAutopilot (Float64 FlightTime, AirframeStruct & AirframeData, AerodynamicStruct & AeroData, GuidanceStruct & GuidanceData, ActuatorStruct & ActuatorData, IMUStruct & IMUData, NavigationStruct & NavData)
calculate controlls
Parameters
FlightTime flight time
AirframeData flight states
AeroData get angle of attack
GuidanceData control input
ActuatorData actuator angles
IMUData rotatory rates
NavData velocity
Definition at line 19 of file Autopilot.cpp.
Referenced by RealSystemTrajectory::updateTrajectory(), and Trajectory6Dof::updateTrajectory().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/Autopilot.h
C:/Users/janol/Desktop/Simulation_Stand230618/Autopilot/Autopilot.cpp