BaseActuator Class Reference
#include <BaseActuator.h>
Public Member Functions
BaseActuator ()
construtor
~BaseActuator ()
construtor
virtual void initActuator (Float64 &FlightTime, AirframeStruct &AirframeData, ActuatorStruct &ActuatorData)
initialize selected actuator model
virtual void updateActuator (Float64 FlightTime, AirframeStruct &AirframeData, ActuatorStruct &ActuatorData)
update actuator model
virtual void LogActuatorData ()
log Actuator data
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
BaseActuator class is the superclass for all actuator models. Using pointer to base init and update function allows the user to extend the actuators module with new models.
Definition at line 19 of file BaseActuator.h.
Constructor & Destructor Documentation
BaseActuator()
BaseActuator::BaseActuator ()
construtor
Definition at line 3 of file BaseActuator.cpp.
 BaseActuator()
BaseActuator::~BaseActuator ()
construtor
Definition at line 7 of file BaseActuator.cpp.
Member Function Documentation
initActuator()
void BaseActuator::initActuator (Float64 & FlightTime, AirframeStruct & AirframeData, ActuatorStruct & ActuatorData) [virtual]
initialize selected actuator model
Parameters
FlightTime Flight time
AirframeData coammanded actuator angles from autopilot
ActuatorData real Actuator angles
Reimplemented in flawlessActuator.
Definition at line 11 of file BaseActuator.cpp.
Referenced by Actuator::initActuator().
LogActuatorData()
void BaseActuator::LogActuatorData () [virtual]
log Actuator data
Reimplemented in flawlessActuator.
Definition at line 23 of file BaseActuator.cpp.
Referenced by Actuator::logActuator().
updateActuator()
void BaseActuator::updateActuator (Float64 FlightTime, AirframeStruct & AirframeData, ActuatorStruct & ActuatorData) [virtual]
update actuator model
Parameters
FlightTime Flight time
AirframeData coammanded actuator angles from autopilot
ActuatorData real Actuator angles
Reimplemented in flawlessActuator.
Definition at line 17 of file BaseActuator.cpp.
Referenced by Actuator::updateActuator().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Actuator/BaseActuator.h
C:/Users/janol/Desktop/Simulation_Stand230618/Actuator/BaseActuator.cpp