MatFileReader Class Reference
#include <MatFileReader.h>
Public Member Functions
MatFileReader (const char *filename)
constructor
~MatFileReader ()
destructor
std::tuple< Eigen::MatrixXd, Eigen::VectorXd, Float64, Eigen::RowVectorXd > readMatFileStructure (const char *FieldName, int &start, int &stride, int &edge, int &copy_fields)
reads in .mat files that cotains of structures (specific for gain scheduling controller)
std::tuple< Eigen::MatrixXd, Eigen::VectorXd, Float64, Eigen::RowVectorXd > readMatFileData (const char *FieldName)
reads in .mat files that cotains only variables
matvar_t getMatFileInfo (const char *MatFileName)
get basic information about the .mat-file
Detailed Description
Author
Jan Olucak
Date
25.11.2017
Version
1.0
MatFileReader class provides functions to read in compressed .mat-Files. All functions are based in the main on the matio library of Christopher C. Hulbert (see above copyright)
Definition at line 57 of file MatFileReader.h.
Constructor & Destructor Documentation
MatFileReader()
MatFileReader::MatFileReader (const char * filename)
constructor
Parameters
filename name of specific .mat-file
Definition at line 4 of file MatFileReader.cpp.
 MatFileReader()
MatFileReader::~MatFileReader ()
destructor
Definition at line 18 of file MatFileReader.cpp.
Member Function Documentation
getMatFileInfo()
matvar_t MatFileReader::getMatFileInfo (const char * MatFileName)
get basic information about the .mat-file
Parameters
MatFileName name of .mat-File
Definition at line 130 of file MatFileReader.cpp.
Referenced by FindNeighbor::initFindNeighbor(), StateController::initStateController(), Aircraft::simulateAircraft(), and TrajectoryTest().
readMatFileData()
std::tuple< Eigen::MatrixXd, Eigen::VectorXd, Float64, Eigen::RowVectorXd > MatFileReader::readMatFileData (const char * FieldName)
reads in .mat files that cotains only variables
Parameters
FieldName name of desired field
Definition at line 96 of file MatFileReader.cpp.
Referenced by DATCOMAerodymamic::initAerodynamic(), accTable::initGuidance(), and UnitTest1::TEST_CLASS().
readMatFileStructure()
std::tuple< Eigen::MatrixXd, Eigen::VectorXd, Float64, Eigen::RowVectorXd > MatFileReader::readMatFileStructure (const char * FieldName, int & start, int & stride, int & edge, int & copy_fields)
reads in .mat files that cotains of structures (specific for gain scheduling controller)
Parameters
FieldName name of desired field
start
stride
edge
copy_fields
Definition at line 24 of file MatFileReader.cpp.
Referenced by FindNeighbor::initFindNeighbor(), StateController::initStateController(), Aircraft::simulateAircraft(), and TrajectoryTest().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/MatFileReader.h
C:/Users/janol/Desktop/Simulation_Stand230618/Tools/MatFileReader.cpp