Trajectory Class Reference
#include <Trajectory.h>
Public Member Functions
Trajectory (SimDPreference &SimPref)
constructor
~Trajectory ()
destructor
void selectTrajectory (int type, SimDPreference &SimPref)
switch function to select desired trajecotry model
void updateTrajectory (Float64 FlightTime, AtmosphereStruct &AtmoData, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
calculate trajectory
void initTrajectory (Float64 &FlightTime, AerodynamicStruct &AeroData, AirframeStruct &AirframeData, ThrustStruct &ThrustData, AircraftStruct &AircraftData, GuidanceStruct &GuidanceData, NavigationStruct &NavData, ActuatorStruct &ActuatorData, IMUStruct &IMUData)
initalize trajectory
void logTraj ()
log trajectory data
Detailed Description
Definition at line 18 of file Trajectory.h.
Constructor & Destructor Documentation
Trajectory()
Trajectory::Trajectory (SimDPreference & SimPref)
constructor
Parameters
SimPref mode selection for trajectory
Definition at line 3 of file Trajectory.cpp.
 Trajectory()
Trajectory::~Trajectory ()
destructor
Definition at line 9 of file Trajectory.cpp.
Member Function Documentation
initTrajectory()
void Trajectory::initTrajectory (Float64 & FlightTime, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, AircraftStruct & AircraftData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData)
initalize trajectory
Parameters
FlightTime flight time
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
AircraftData geometric data of aircraft
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Definition at line 59 of file Trajectory.cpp.
Referenced by Aircraft::simulateAircraft(), and TrajectoryTest().
logTraj()
void Trajectory::logTraj ()
log trajectory data
Definition at line 81 of file Trajectory.cpp.
selectTrajectory()
void Trajectory::selectTrajectory (int type, SimDPreference & SimPref)
switch function to select desired trajecotry model
Parameters
type trajectory model
SimPref selection of module models
Definition at line 13 of file Trajectory.cpp.
Referenced by Trajectory().
updateTrajectory()
void Trajectory::updateTrajectory (Float64 FlightTime, AtmosphereStruct & AtmoData, AerodynamicStruct & AeroData, AirframeStruct & AirframeData, ThrustStruct & ThrustData, GuidanceStruct & GuidanceData, NavigationStruct & NavData, ActuatorStruct & ActuatorData, IMUStruct & IMUData)
calculate trajectory
Parameters
FlightTime flight time
AtmoData current atmospheric data
AeroData aerodynamic data
AirframeData flight states
ThrustData thrust forces and moments
GuidanceData control variables
NavData aircraft position, velocity
ActuatorData real actuator angles
IMUData measured acceleration
Definition at line 38 of file Trajectory.cpp.
Referenced by Aircraft::simulateAircraft(), and TrajectoryTest().
The documentation for this class was generated from the following files:
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory.h
C:/Users/janol/Desktop/Simulation_Stand230618/Trajectory/Trajectory.cpp