var searchData=
[
  ['scalar_5fabs2_5fop',['scalar_abs2_op',['../struct_eigen_1_1internal_1_1scalar__abs2__op.html',1,'Eigen::internal']]],
  ['scalar_5fabs_5fop',['scalar_abs_op',['../struct_eigen_1_1internal_1_1scalar__abs__op.html',1,'Eigen::internal']]],
  ['scalar_5facos_5fop',['scalar_acos_op',['../struct_eigen_1_1internal_1_1scalar__acos__op.html',1,'Eigen::internal']]],
  ['scalar_5farg_5fop',['scalar_arg_op',['../struct_eigen_1_1internal_1_1scalar__arg__op.html',1,'Eigen::internal']]],
  ['scalar_5fasin_5fop',['scalar_asin_op',['../struct_eigen_1_1internal_1_1scalar__asin__op.html',1,'Eigen::internal']]],
  ['scalar_5fatan_5fop',['scalar_atan_op',['../struct_eigen_1_1internal_1_1scalar__atan__op.html',1,'Eigen::internal']]],
  ['scalar_5fbetainc_5fop',['scalar_betainc_op',['../struct_eigen_1_1internal_1_1scalar__betainc__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fand_5fop',['scalar_boolean_and_op',['../struct_eigen_1_1internal_1_1scalar__boolean__and__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fnot_5fop',['scalar_boolean_not_op',['../struct_eigen_1_1internal_1_1scalar__boolean__not__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5for_5fop',['scalar_boolean_or_op',['../struct_eigen_1_1internal_1_1scalar__boolean__or__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fxor_5fop',['scalar_boolean_xor_op',['../struct_eigen_1_1internal_1_1scalar__boolean__xor__op.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop',['scalar_cast_op',['../struct_eigen_1_1internal_1_1scalar__cast__op.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20eigen_3a_3ahalf_2c_20float_20_3e',['scalar_cast_op&lt; Eigen::half, float &gt;',['../struct_eigen_1_1internal_1_1scalar__cast__op_3_01_eigen_1_1half_00_01float_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20float_2c_20eigen_3a_3ahalf_20_3e',['scalar_cast_op&lt; float, Eigen::half &gt;',['../struct_eigen_1_1internal_1_1scalar__cast__op_3_01float_00_01_eigen_1_1half_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop_3c_20int_2c_20eigen_3a_3ahalf_20_3e',['scalar_cast_op&lt; int, Eigen::half &gt;',['../struct_eigen_1_1internal_1_1scalar__cast__op_3_01int_00_01_eigen_1_1half_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fceil_5fop',['scalar_ceil_op',['../struct_eigen_1_1internal_1_1scalar__ceil__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop',['scalar_cmp_op',['../struct_eigen_1_1internal_1_1scalar__cmp__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5feq_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_EQ &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___e_q_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fge_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_GE &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___g_e_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fgt_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_GT &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___g_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fle_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_LE &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___l_e_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5flt_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_LT &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___l_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5fneq_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_NEQ &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___n_e_q_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20lhsscalar_2c_20rhsscalar_2c_20cmp_5funord_20_3e',['scalar_cmp_op&lt; LhsScalar, RhsScalar, cmp_UNORD &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_lhs_scalar_00_01_rhs_scalar_00_01cmp___u_n_o_r_d_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fconj_5fproduct_5fop',['scalar_conj_product_op',['../struct_eigen_1_1internal_1_1scalar__conj__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fconjugate_5fop',['scalar_conjugate_op',['../struct_eigen_1_1internal_1_1scalar__conjugate__op.html',1,'Eigen::internal']]],
  ['scalar_5fconstant_5fop',['scalar_constant_op',['../struct_eigen_1_1internal_1_1scalar__constant__op.html',1,'Eigen::internal']]],
  ['scalar_5fcos_5fop',['scalar_cos_op',['../struct_eigen_1_1internal_1_1scalar__cos__op.html',1,'Eigen::internal']]],
  ['scalar_5fcosh_5fop',['scalar_cosh_op',['../struct_eigen_1_1internal_1_1scalar__cosh__op.html',1,'Eigen::internal']]],
  ['scalar_5fcube_5fop',['scalar_cube_op',['../struct_eigen_1_1internal_1_1scalar__cube__op.html',1,'Eigen::internal']]],
  ['scalar_5fdifference_5fop',['scalar_difference_op',['../struct_eigen_1_1internal_1_1scalar__difference__op.html',1,'Eigen::internal']]],
  ['scalar_5fdigamma_5fop',['scalar_digamma_op',['../struct_eigen_1_1internal_1_1scalar__digamma__op.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost',['scalar_div_cost',['../struct_eigen_1_1internal_1_1scalar__div__cost.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20double_2c_20true_20_3e',['scalar_div_cost&lt; double, true &gt;',['../struct_eigen_1_1internal_1_1scalar__div__cost_3_01double_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20float_2c_20true_20_3e',['scalar_div_cost&lt; float, true &gt;',['../struct_eigen_1_1internal_1_1scalar__div__cost_3_01float_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20signed_20long_2c_20vectorized_2c_20typename_20conditional_3c_20sizeof_28long_29_3d_3d8_2c_20void_2c_20false_5ftype_20_3e_3a_3atype_20_3e',['scalar_div_cost&lt; signed long, Vectorized, typename conditional&lt; sizeof(long)==8, void, false_type &gt;::type &gt;',['../struct_eigen_1_1internal_1_1scalar__div__cost_3_01signed_01long_00_01_vectorized_00_01typename_0928d7226c6d88e74072f0f5e87ecaa67.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20std_3a_3acomplex_3c_20t_20_3e_2c_20vectorized_20_3e',['scalar_div_cost&lt; std::complex&lt; T &gt;, Vectorized &gt;',['../struct_eigen_1_1internal_1_1scalar__div__cost_3_01std_1_1complex_3_01_t_01_4_00_01_vectorized_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fdiv_5fcost_3c_20unsigned_20long_2c_20vectorized_2c_20typename_20conditional_3c_20sizeof_28long_29_3d_3d8_2c_20void_2c_20false_5ftype_20_3e_3a_3atype_20_3e',['scalar_div_cost&lt; unsigned long, Vectorized, typename conditional&lt; sizeof(long)==8, void, false_type &gt;::type &gt;',['../struct_eigen_1_1internal_1_1scalar__div__cost_3_01unsigned_01long_00_01_vectorized_00_01typenamea197e29684b99203d4e90be10117c3ad.html',1,'Eigen::internal']]],
  ['scalar_5ferf_5fop',['scalar_erf_op',['../struct_eigen_1_1internal_1_1scalar__erf__op.html',1,'Eigen::internal']]],
  ['scalar_5ferfc_5fop',['scalar_erfc_op',['../struct_eigen_1_1internal_1_1scalar__erfc__op.html',1,'Eigen::internal']]],
  ['scalar_5fexp_5fop',['scalar_exp_op',['../struct_eigen_1_1internal_1_1scalar__exp__op.html',1,'Eigen::internal']]],
  ['scalar_5ffloor_5fop',['scalar_floor_op',['../struct_eigen_1_1internal_1_1scalar__floor__op.html',1,'Eigen::internal']]],
  ['scalar_5ffmod_5fop',['scalar_fmod_op',['../struct_eigen_1_1internal_1_1scalar__fmod__op.html',1,'Eigen::internal']]],
  ['scalar_5fhypot_5fop',['scalar_hypot_op',['../struct_eigen_1_1internal_1_1scalar__hypot__op.html',1,'Eigen::internal']]],
  ['scalar_5fhypot_5fop_3c_20scalar_2c_20scalar_20_3e',['scalar_hypot_op&lt; Scalar, Scalar &gt;',['../struct_eigen_1_1internal_1_1scalar__hypot__op_3_01_scalar_00_01_scalar_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fidentity_5fop',['scalar_identity_op',['../struct_eigen_1_1internal_1_1scalar__identity__op.html',1,'Eigen::internal']]],
  ['scalar_5figamma_5fop',['scalar_igamma_op',['../struct_eigen_1_1internal_1_1scalar__igamma__op.html',1,'Eigen::internal']]],
  ['scalar_5figammac_5fop',['scalar_igammac_op',['../struct_eigen_1_1internal_1_1scalar__igammac__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fop',['scalar_imag_op',['../struct_eigen_1_1internal_1_1scalar__imag__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fref_5fop',['scalar_imag_ref_op',['../struct_eigen_1_1internal_1_1scalar__imag__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5finverse_5fop',['scalar_inverse_op',['../struct_eigen_1_1internal_1_1scalar__inverse__op.html',1,'Eigen::internal']]],
  ['scalar_5fisfinite_5fop',['scalar_isfinite_op',['../struct_eigen_1_1internal_1_1scalar__isfinite__op.html',1,'Eigen::internal']]],
  ['scalar_5fisinf_5fop',['scalar_isinf_op',['../struct_eigen_1_1internal_1_1scalar__isinf__op.html',1,'Eigen::internal']]],
  ['scalar_5fisnan_5fop',['scalar_isnan_op',['../struct_eigen_1_1internal_1_1scalar__isnan__op.html',1,'Eigen::internal']]],
  ['scalar_5flgamma_5fop',['scalar_lgamma_op',['../struct_eigen_1_1internal_1_1scalar__lgamma__op.html',1,'Eigen::internal']]],
  ['scalar_5flog10_5fop',['scalar_log10_op',['../struct_eigen_1_1internal_1_1scalar__log10__op.html',1,'Eigen::internal']]],
  ['scalar_5flog1p_5fop',['scalar_log1p_op',['../struct_eigen_1_1internal_1_1scalar__log1p__op.html',1,'Eigen::internal']]],
  ['scalar_5flog_5fop',['scalar_log_op',['../struct_eigen_1_1internal_1_1scalar__log__op.html',1,'Eigen::internal']]],
  ['scalar_5fmax_5fop',['scalar_max_op',['../struct_eigen_1_1internal_1_1scalar__max__op.html',1,'Eigen::internal']]],
  ['scalar_5fmin_5fop',['scalar_min_op',['../struct_eigen_1_1internal_1_1scalar__min__op.html',1,'Eigen::internal']]],
  ['scalar_5fmod2_5fop',['scalar_mod2_op',['../struct_eigen_1_1internal_1_1scalar__mod2__op.html',1,'Eigen::internal']]],
  ['scalar_5fmod_5fop',['scalar_mod_op',['../struct_eigen_1_1internal_1_1scalar__mod__op.html',1,'Eigen::internal']]],
  ['scalar_5fnorm1_5fop',['scalar_norm1_op',['../structscalar__norm1__op.html',1,'']]],
  ['scalar_5fopposite_5fop',['scalar_opposite_op',['../struct_eigen_1_1internal_1_1scalar__opposite__op.html',1,'Eigen::internal']]],
  ['scalar_5fpolygamma_5fop',['scalar_polygamma_op',['../struct_eigen_1_1internal_1_1scalar__polygamma__op.html',1,'Eigen::internal']]],
  ['scalar_5fpow_5fop',['scalar_pow_op',['../struct_eigen_1_1internal_1_1scalar__pow__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5fop',['scalar_product_op',['../struct_eigen_1_1internal_1_1scalar__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits',['scalar_product_traits',['../struct_eigen_1_1internal_1_1scalar__product__traits.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits_3c_20scalara_2c_20scalarb_20_3e',['scalar_product_traits&lt; ScalarA, ScalarB &gt;',['../struct_eigen_1_1internal_1_1scalar__product__traits.html',1,'Eigen::internal']]],
  ['scalar_5fquotient_5fop',['scalar_quotient_op',['../struct_eigen_1_1internal_1_1scalar__quotient__op.html',1,'Eigen::internal']]],
  ['scalar_5frandom_5fop',['scalar_random_op',['../struct_eigen_1_1internal_1_1scalar__random__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fop',['scalar_real_op',['../struct_eigen_1_1internal_1_1scalar__real__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fref_5fop',['scalar_real_ref_op',['../struct_eigen_1_1internal_1_1scalar__real__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5fround_5fop',['scalar_round_op',['../struct_eigen_1_1internal_1_1scalar__round__op.html',1,'Eigen::internal']]],
  ['scalar_5frsqrt_5fop',['scalar_rsqrt_op',['../struct_eigen_1_1internal_1_1scalar__rsqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5fscore_5fcoeff_5fop',['scalar_score_coeff_op',['../struct_eigen_1_1internal_1_1scalar__score__coeff__op.html',1,'Eigen::internal']]],
  ['scalar_5fsigmoid_5fop',['scalar_sigmoid_op',['../struct_eigen_1_1internal_1_1scalar__sigmoid__op.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop',['scalar_sign_op',['../struct_eigen_1_1internal_1_1scalar__sign__op.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop_3c_20scalar_2c_20false_20_3e',['scalar_sign_op&lt; Scalar, false &gt;',['../struct_eigen_1_1internal_1_1scalar__sign__op_3_01_scalar_00_01false_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsign_5fop_3c_20scalar_2c_20true_20_3e',['scalar_sign_op&lt; Scalar, true &gt;',['../struct_eigen_1_1internal_1_1scalar__sign__op_3_01_scalar_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsin_5fop',['scalar_sin_op',['../struct_eigen_1_1internal_1_1scalar__sin__op.html',1,'Eigen::internal']]],
  ['scalar_5fsinh_5fop',['scalar_sinh_op',['../struct_eigen_1_1internal_1_1scalar__sinh__op.html',1,'Eigen::internal']]],
  ['scalar_5fsqrt_5fop',['scalar_sqrt_op',['../struct_eigen_1_1internal_1_1scalar__sqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5fsquare_5fop',['scalar_square_op',['../struct_eigen_1_1internal_1_1scalar__square__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop',['scalar_sum_op',['../struct_eigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20bool_2c_20bool_20_3e',['scalar_sum_op&lt; bool, bool &gt;',['../struct_eigen_1_1internal_1_1scalar__sum__op_3_01bool_00_01bool_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20int_2c_20int_20_3e',['scalar_sum_op&lt; int, int &gt;',['../struct_eigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5ftan_5fop',['scalar_tan_op',['../struct_eigen_1_1internal_1_1scalar__tan__op.html',1,'Eigen::internal']]],
  ['scalar_5ftanh_5fop',['scalar_tanh_op',['../struct_eigen_1_1internal_1_1scalar__tanh__op.html',1,'Eigen::internal']]],
  ['scalar_5fzeta_5fop',['scalar_zeta_op',['../struct_eigen_1_1internal_1_1scalar__zeta__op.html',1,'Eigen::internal']]],
  ['scalarbinaryoptraits',['ScalarBinaryOpTraits',['../struct_eigen_1_1_scalar_binary_op_traits.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20autodiffscalar_3c_20dertype_20_3e_2c_20typename_20dertype_3a_3ascalar_2c_20binop_20_3e',['ScalarBinaryOpTraits&lt; AutoDiffScalar&lt; DerType &gt;, typename DerType::Scalar, BinOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01_auto_diff_scalar_3_01_der_type_01_4_00_01typename_8029eb4becd448e88ba5e4cb75a4dd2b.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, T, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01_t_00_01_t_00_01_binary_op_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20typename_20numtraits_3c_20typename_20internal_3a_3aenable_5fif_3c_20numtraits_3c_20t_20_3e_3a_3aiscomplex_2c_20t_20_3e_3a_3atype_20_3e_3a_3areal_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, typename NumTraits&lt; typename internal::enable_if&lt; NumTraits&lt; T &gt;::IsComplex, T &gt;::type &gt;::Real, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01_t_00_01typename_01_num_traits_3_01typename_01inter6d9b2ba43c8f599c26e1e5ea9727da7f.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20t_2c_20void_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; T, void, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01_t_00_01void_00_01_binary_op_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20typename_20dertype_3a_3ascalar_2c_20autodiffscalar_3c_20dertype_20_3e_2c_20binop_20_3e',['ScalarBinaryOpTraits&lt; typename DerType::Scalar, AutoDiffScalar&lt; DerType &gt;, BinOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01typename_01_der_type_1_1_scalar_00_01_auto_diff_sca5c26207d328bbaa3069a04f38248d36b.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20typename_20numtraits_3c_20typename_20internal_3a_3aenable_5fif_3c_20numtraits_3c_20t_20_3e_3a_3aiscomplex_2c_20t_20_3e_3a_3atype_20_3e_3a_3areal_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; typename NumTraits&lt; typename internal::enable_if&lt; NumTraits&lt; T &gt;::IsComplex, T &gt;::type &gt;::Real, T, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01typename_01_num_traits_3_01typename_01internal_1_1e682c29bad5c4221eece44bbf2be041d0.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20void_2c_20t_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; void, T, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01void_00_01_t_00_01_binary_op_01_4.html',1,'Eigen']]],
  ['scalarbinaryoptraits_3c_20void_2c_20void_2c_20binaryop_20_3e',['ScalarBinaryOpTraits&lt; void, void, BinaryOp &gt;',['../struct_eigen_1_1_scalar_binary_op_traits_3_01void_00_01void_00_01_binary_op_01_4.html',1,'Eigen']]],
  ['scalarwithexceptions',['ScalarWithExceptions',['../class_scalar_with_exceptions.html',1,'']]],
  ['scaling',['Scaling',['../class_scaling.html',1,'Scaling'],['../class_scaling.html',1,'Scaling']]],
  ['scanlauncher',['ScanLauncher',['../struct_eigen_1_1_scan_launcher.html',1,'Eigen']]],
  ['scoped_5farray',['scoped_array',['../class_eigen_1_1internal_1_1scoped__array.html',1,'Eigen::internal']]],
  ['select',['Select',['../class_eigen_1_1_select.html',1,'Eigen']]],
  ['selector',['Selector',['../struct_eigen_1_1internal_1_1_selector.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct',['selfadjoint_matrix_vector_product',['../struct_eigen_1_1internal_1_1selfadjoint__matrix__vector__product.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct_3c_20scalar_2c_20index_2c_20storageorder_2c_20uplo_2c_20conjugatelhs_2c_20conjugaterhs_2c_20builtin_20_3e',['selfadjoint_matrix_vector_product&lt; Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, BuiltIn &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__matrix__vector__product.html',1,'Eigen::internal']]],
  ['selfadjoint_5fmatrix_5fvector_5fproduct_5fsymv',['selfadjoint_matrix_vector_product_symv',['../struct_eigen_1_1internal_1_1selfadjoint__matrix__vector__product__symv.html',1,'Eigen::internal']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate',['selfadjoint_packed_rank1_update',['../structinternal_1_1selfadjoint__packed__rank1__update.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, StorageOrder, UpLo, ConjLhs, ConjRhs &gt;'],['../struct_eigen_1_1internal_1_1selfadjoint__packed__rank1__update.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, StorageOrder, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20colmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structinternal_1_1selfadjoint__packed__rank1__update_3_01_scalar_00_01_index_00_01_col_major_00_cda55a2b2bf1b1755d1ad2703b37584d.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;'],['../struct_eigen_1_1internal_1_1selfadjoint__packed__rank1__update_3_01_scalar_00_01_index_00_01_col211b56a6e7dbb087a746c109f1fd6193.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fpacked_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20rowmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;',['../structinternal_1_1selfadjoint__packed__rank1__update_3_01_scalar_00_01_index_00_01_row_major_00_9e7850f711875a82e66e0710a9772df5.html',1,'internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;'],['../struct_eigen_1_1internal_1_1selfadjoint__packed__rank1__update_3_01_scalar_00_01_index_00_01_row44ee905dfbb7f4c0a9e13e624ea4a89c.html',1,'Eigen::internal::selfadjoint_packed_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;']]],
  ['selfadjoint_5fproduct_5fimpl',['selfadjoint_product_impl',['../struct_eigen_1_1internal_1_1selfadjoint__product__impl.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_200_2c_20true_2c_20rhs_2c_20rhsmode_2c_20false_20_3e',['selfadjoint_product_impl&lt; Lhs, 0, true, Rhs, RhsMode, false &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__product__impl_3_01_lhs_00_010_00_01true_00_01_rhs_00_01_rhs_mode_00_01false_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_20lhsmode_2c_20false_2c_20rhs_2c_200_2c_20true_20_3e',['selfadjoint_product_impl&lt; Lhs, LhsMode, false, Rhs, 0, true &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__product__impl_3_01_lhs_00_01_lhs_mode_00_01false_00_01_rhs_00_010_00_01true_01_4.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl_3c_20lhs_2c_20lhsmode_2c_20false_2c_20rhs_2c_20rhsmode_2c_20false_20_3e',['selfadjoint_product_impl&lt; Lhs, LhsMode, false, Rhs, RhsMode, false &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__product__impl_3_01_lhs_00_01_lhs_mode_00_01false_00_01_0e7941e7b3bc2131c413f23ec856f76c.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fselector',['selfadjoint_product_selector',['../struct_eigen_1_1selfadjoint__product__selector.html',1,'Eigen']]],
  ['selfadjoint_5fproduct_5fselector_3c_20matrixtype_2c_20othertype_2c_20uplo_2c_20false_20_3e',['selfadjoint_product_selector&lt; MatrixType, OtherType, UpLo, false &gt;',['../struct_eigen_1_1selfadjoint__product__selector_3_01_matrix_type_00_01_other_type_00_01_up_lo_00_01false_01_4.html',1,'Eigen']]],
  ['selfadjoint_5fproduct_5fselector_3c_20matrixtype_2c_20othertype_2c_20uplo_2c_20true_20_3e',['selfadjoint_product_selector&lt; MatrixType, OtherType, UpLo, true &gt;',['../struct_eigen_1_1selfadjoint__product__selector_3_01_matrix_type_00_01_other_type_00_01_up_lo_00_01true_01_4.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate',['selfadjoint_rank1_update',['../struct_eigen_1_1selfadjoint__rank1__update.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20colmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_rank1_update&lt; Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs &gt;',['../struct_eigen_1_1selfadjoint__rank1__update_3_01_scalar_00_01_index_00_01_col_major_00_01_up_lo_0985162e7429113fdcd7a3950b8d00f1e.html',1,'Eigen']]],
  ['selfadjoint_5frank1_5fupdate_3c_20scalar_2c_20index_2c_20rowmajor_2c_20uplo_2c_20conjlhs_2c_20conjrhs_20_3e',['selfadjoint_rank1_update&lt; Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs &gt;',['../struct_eigen_1_1selfadjoint__rank1__update_3_01_scalar_00_01_index_00_01_row_major_00_01_up_lo_03a9dcf0deae11b1da493e4caae5cd21a.html',1,'Eigen']]],
  ['selfadjoint_5frank2_5fupdate_5fselector',['selfadjoint_rank2_update_selector',['../struct_eigen_1_1internal_1_1selfadjoint__rank2__update__selector.html',1,'Eigen::internal']]],
  ['selfadjoint_5frank2_5fupdate_5fselector_3c_20scalar_2c_20index_2c_20utype_2c_20vtype_2c_20lower_20_3e',['selfadjoint_rank2_update_selector&lt; Scalar, Index, UType, VType, Lower &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__rank2__update__selector_3_01_scalar_00_01_index_00_01_uf491e100c52e514fc778fd2dd4e730f2.html',1,'Eigen::internal']]],
  ['selfadjoint_5frank2_5fupdate_5fselector_3c_20scalar_2c_20index_2c_20utype_2c_20vtype_2c_20upper_20_3e',['selfadjoint_rank2_update_selector&lt; Scalar, Index, UType, VType, Upper &gt;',['../struct_eigen_1_1internal_1_1selfadjoint__rank2__update__selector_3_01_scalar_00_01_index_00_01_uf7a068ce7ab78b9bb81bd0ca858e99d2.html',1,'Eigen::internal']]],
  ['selfadjointeigensolver',['SelfAdjointEigenSolver',['../class_eigen_1_1_self_adjoint_eigen_solver.html',1,'Eigen']]],
  ['selfadjointshape',['SelfAdjointShape',['../struct_eigen_1_1_self_adjoint_shape.html',1,'Eigen']]],
  ['selfadjointview',['SelfAdjointView',['../class_eigen_1_1_self_adjoint_view.html',1,'Eigen']]],
  ['selfadjointviewreturntype',['SelfAdjointViewReturnType',['../struct_eigen_1_1_matrix_base_1_1_self_adjoint_view_return_type.html',1,'Eigen::MatrixBase&lt; Derived &gt;::SelfAdjointViewReturnType&lt; UpLo &gt;'],['../struct_eigen_1_1_sparse_matrix_base_1_1_self_adjoint_view_return_type.html',1,'Eigen::SparseMatrixBase&lt; Derived &gt;::SelfAdjointViewReturnType&lt; UpLo &gt;']]],
  ['sensor_5ft',['sensor_t',['../structsensor__t.html',1,'']]],
  ['set',['set',['../struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_dense_shape_00_01_de53b08926de0225703046b27d8aadeb7a.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['setidentity_5fimpl',['setIdentity_impl',['../struct_eigen_1_1internal_1_1set_identity__impl.html',1,'Eigen::internal']]],
  ['setidentity_5fimpl_3c_20derived_2c_20true_20_3e',['setIdentity_impl&lt; Derived, true &gt;',['../struct_eigen_1_1internal_1_1set_identity__impl_3_01_derived_00_01true_01_4.html',1,'Eigen::internal']]],
  ['sgroup',['SGroup',['../class_eigen_1_1_s_group.html',1,'Eigen']]],
  ['significant_5fdecimals_5fimpl',['significant_decimals_impl',['../struct_eigen_1_1internal_1_1significant__decimals__impl.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper',['SimpleTensorContractionMapper',['../class_eigen_1_1internal_1_1_simple_tensor_contraction_mapper.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper_3c_20scalar_2c_20index_2c_20side_2c_20tensor_2c_20nocontract_5ft_2c_20contract_5ft_2c_201_2c_20inner_5fdim_5fcontiguous_2c_20alignment_20_3e',['SimpleTensorContractionMapper&lt; Scalar, Index, side, Tensor, nocontract_t, contract_t, 1, inner_dim_contiguous, Alignment &gt;',['../class_eigen_1_1internal_1_1_simple_tensor_contraction_mapper.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper_3c_20scalar_5f_2c_20index_2c_20side_2c_20tensor_2c_20nocontract_5ft_2c_20contract_5ft_2c_20packet_5fsize_2c_20inner_5fdim_5fcontiguous_2c_20alignment_20_3e',['SimpleTensorContractionMapper&lt; Scalar_, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment &gt;',['../class_eigen_1_1internal_1_1_simple_tensor_contraction_mapper.html',1,'Eigen::internal']]],
  ['simplethreadpooltempl',['SimpleThreadPoolTempl',['../class_eigen_1_1_simple_thread_pool_templ.html',1,'Eigen']]],
  ['simplicial_5fcholesky_5fgrab_5finput',['simplicial_cholesky_grab_input',['../struct_eigen_1_1internal_1_1simplicial__cholesky__grab__input.html',1,'Eigen::internal']]],
  ['simplicial_5fcholesky_5fgrab_5finput_3c_20matrixtype_2c_20matrixtype_20_3e',['simplicial_cholesky_grab_input&lt; MatrixType, MatrixType &gt;',['../struct_eigen_1_1internal_1_1simplicial__cholesky__grab__input_3_01_matrix_type_00_01_matrix_type_01_4.html',1,'Eigen::internal']]],
  ['simplicialcholesky',['SimplicialCholesky',['../class_eigen_1_1_simplicial_cholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase',['SimplicialCholeskyBase',['../class_eigen_1_1_simplicial_cholesky_base.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_simplicial_cholesky_base.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_simplicial_cholesky_base.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_simplicial_cholesky_base.html',1,'Eigen']]],
  ['simplicialldlt',['SimplicialLDLT',['../class_eigen_1_1_simplicial_l_d_l_t.html',1,'Eigen']]],
  ['simplicialllt',['SimplicialLLT',['../class_eigen_1_1_simplicial_l_l_t.html',1,'Eigen']]],
  ['singletonvector',['SingletonVector',['../class_eigen_1_1_sparse_matrix_1_1_singleton_vector.html',1,'Eigen::SparseMatrix']]],
  ['size_5fat_5fcompile_5ftime',['size_at_compile_time',['../struct_eigen_1_1internal_1_1size__at__compile__time.html',1,'Eigen::internal']]],
  ['size_5fof_5fxpr_5fat_5fcompile_5ftime',['size_of_xpr_at_compile_time',['../struct_eigen_1_1internal_1_1size__of__xpr__at__compile__time.html',1,'Eigen::internal']]],
  ['size_5ftriple_5ft',['size_triple_t',['../structsize__triple__t.html',1,'']]],
  ['sizes',['Sizes',['../struct_eigen_1_1_sizes.html',1,'Eigen']]],
  ['sizes_5fmatch_5fbelow_5fdim',['sizes_match_below_dim',['../struct_eigen_1_1internal_1_1sizes__match__below__dim.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_200_2c_200_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, 0, 0 &gt;',['../struct_eigen_1_1internal_1_1sizes__match__below__dim_3_01_dims1_00_01_dims2_00_010_00_010_01_4.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_20n_2c_20n_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, n, n &gt;',['../struct_eigen_1_1internal_1_1sizes__match__below__dim_3_01_dims1_00_01_dims2_00_01n_00_01n_01_4.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fmode',['skyline_product_mode',['../struct_eigen_1_1internal_1_1skyline__product__mode.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector',['skyline_product_selector',['../struct_eigen_1_1internal_1_1skyline__product__selector.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_20_3e',['skyline_product_selector&lt; Lhs, Rhs, ResultType, ColMajor &gt;',['../struct_eigen_1_1internal_1_1skyline__product__selector_3_01_lhs_00_01_rhs_00_01_result_type_00_01_col_major_01_4.html',1,'Eigen::internal']]],
  ['skyline_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_20_3e',['skyline_product_selector&lt; Lhs, Rhs, ResultType, RowMajor &gt;',['../struct_eigen_1_1internal_1_1skyline__product__selector_3_01_lhs_00_01_rhs_00_01_result_type_00_01_row_major_01_4.html',1,'Eigen::internal']]],
  ['skylineinplacelu',['SkylineInplaceLU',['../class_eigen_1_1_skyline_inplace_l_u.html',1,'Eigen']]],
  ['skylinematrix',['SkylineMatrix',['../class_eigen_1_1_skyline_matrix.html',1,'Eigen']]],
  ['skylinematrixbase',['SkylineMatrixBase',['../class_eigen_1_1_skyline_matrix_base.html',1,'Eigen']]],
  ['skylinematrixbase_3c_20skylinematrix_3c_20_5fscalar_2c_20_5foptions_20_3e_20_3e',['SkylineMatrixBase&lt; SkylineMatrix&lt; _Scalar, _Options &gt; &gt;',['../class_eigen_1_1_skyline_matrix_base.html',1,'Eigen']]],
  ['skylineproduct',['SkylineProduct',['../class_eigen_1_1_skyline_product.html',1,'Eigen::SkylineProduct&lt; Lhs, Rhs, ProductMode &gt;'],['../class_eigen_1_1internal_1_1_skyline_product.html',1,'Eigen::internal::SkylineProduct&lt; LhsNested, RhsNested, ProductMode &gt;']]],
  ['skylineproductreturntype',['SkylineProductReturnType',['../struct_eigen_1_1internal_1_1_skyline_product_return_type.html',1,'Eigen::internal::SkylineProductReturnType&lt; Lhs, Rhs, ProductMode &gt;'],['../struct_eigen_1_1_skyline_product_return_type.html',1,'Eigen::SkylineProductReturnType&lt; Lhs, Rhs, ProductMode &gt;']]],
  ['skylinestorage',['SkylineStorage',['../class_eigen_1_1_skyline_storage.html',1,'Eigen']]],
  ['skylinevector',['SkylineVector',['../class_eigen_1_1_skyline_vector.html',1,'Eigen']]],
  ['slumatrix',['SluMatrix',['../struct_eigen_1_1_slu_matrix.html',1,'Eigen']]],
  ['slumatrixmaphelper',['SluMatrixMapHelper',['../struct_eigen_1_1_slu_matrix_map_helper.html',1,'Eigen']]],
  ['slumatrixmaphelper_3c_20matrix_3c_20scalar_2c_20rows_2c_20cols_2c_20options_2c_20mrows_2c_20mcols_20_3e_20_3e',['SluMatrixMapHelper&lt; Matrix&lt; Scalar, Rows, Cols, Options, MRows, MCols &gt; &gt;',['../struct_eigen_1_1_slu_matrix_map_helper_3_01_matrix_3_01_scalar_00_01_rows_00_01_cols_00_01_optioce31c400c0dc6b34c9e9bbf922bc7aae.html',1,'Eigen']]],
  ['slumatrixmaphelper_3c_20sparsematrixbase_3c_20derived_20_3e_20_3e',['SluMatrixMapHelper&lt; SparseMatrixBase&lt; Derived &gt; &gt;',['../struct_eigen_1_1_slu_matrix_map_helper_3_01_sparse_matrix_base_3_01_derived_01_4_01_4.html',1,'Eigen']]],
  ['smart_5fcopy_5fhelper',['smart_copy_helper',['../struct_eigen_1_1internal_1_1smart__copy__helper.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20false_20_3e',['smart_copy_helper&lt; T, false &gt;',['../struct_eigen_1_1internal_1_1smart__copy__helper_3_01_t_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20true_20_3e',['smart_copy_helper&lt; T, true &gt;',['../struct_eigen_1_1internal_1_1smart__copy__helper_3_01_t_00_01true_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper',['smart_memmove_helper',['../struct_eigen_1_1internal_1_1smart__memmove__helper.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20false_20_3e',['smart_memmove_helper&lt; T, false &gt;',['../struct_eigen_1_1internal_1_1smart__memmove__helper_3_01_t_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20true_20_3e',['smart_memmove_helper&lt; T, true &gt;',['../struct_eigen_1_1internal_1_1smart__memmove__helper_3_01_t_00_01true_01_4.html',1,'Eigen::internal']]],
  ['solve',['Solve',['../class_eigen_1_1_solve.html',1,'Eigen']]],
  ['solve_5ftraits',['solve_traits',['../struct_eigen_1_1internal_1_1solve__traits.html',1,'Eigen::internal']]],
  ['solve_5ftraits_3c_20decomposition_2c_20rhstype_2c_20dense_20_3e',['solve_traits&lt; Decomposition, RhsType, Dense &gt;',['../struct_eigen_1_1internal_1_1solve__traits_3_01_decomposition_00_01_rhs_type_00_01_dense_01_4.html',1,'Eigen::internal']]],
  ['solve_5ftraits_3c_20decomposition_2c_20rhstype_2c_20sparse_20_3e',['solve_traits&lt; Decomposition, RhsType, Sparse &gt;',['../struct_eigen_1_1internal_1_1solve__traits_3_01_decomposition_00_01_rhs_type_00_01_sparse_01_4.html',1,'Eigen::internal']]],
  ['solveimpl',['SolveImpl',['../class_eigen_1_1_solve_impl.html',1,'Eigen']]],
  ['solveimpl_3c_20decomposition_2c_20rhstype_2c_20dense_20_3e',['SolveImpl&lt; Decomposition, RhsType, Dense &gt;',['../class_eigen_1_1_solve_impl_3_01_decomposition_00_01_rhs_type_00_01_dense_01_4.html',1,'Eigen']]],
  ['solveimpl_3c_20decomposition_2c_20rhstype_2c_20internal_3a_3atraits_3c_20rhstype_20_3e_3a_3astoragekind_20_3e',['SolveImpl&lt; Decomposition, RhsType, internal::traits&lt; RhsType &gt;::StorageKind &gt;',['../class_eigen_1_1_solve_impl.html',1,'Eigen']]],
  ['solverbase',['SolverBase',['../class_eigen_1_1_solver_base.html',1,'Eigen']]],
  ['solverbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; FullPivLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_solver_base.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20_5fmatrixtype_20_3e_20_3e',['SolverBase&lt; PartialPivLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_solver_base.html',1,'Eigen']]],
  ['solverbase_3c_20partialpivlu_3c_20matrix_3c_20scalar_2c_20dynamic_2c_20dynamic_20_3e_20_3e_20_3e',['SolverBase&lt; PartialPivLU&lt; Matrix&lt; Scalar, Dynamic, Dynamic &gt; &gt; &gt;',['../class_eigen_1_1_solver_base.html',1,'Eigen']]],
  ['solvershape',['SolverShape',['../struct_eigen_1_1_solver_shape.html',1,'Eigen']]],
  ['solverstorage',['SolverStorage',['../struct_eigen_1_1_solver_storage.html',1,'Eigen']]],
  ['solvewithguess',['SolveWithGuess',['../class_eigen_1_1_solve_with_guess.html',1,'Eigen']]],
  ['some_5fnon_5fvectorizable_5ftype',['some_non_vectorizable_type',['../structsome__non__vectorizable__type.html',1,'']]],
  ['sparse',['Sparse',['../struct_eigen_1_1_sparse.html',1,'Eigen']]],
  ['sparse2dense',['Sparse2Dense',['../struct_eigen_1_1internal_1_1_sparse2_dense.html',1,'Eigen::internal']]],
  ['sparse2sparse',['Sparse2Sparse',['../struct_eigen_1_1internal_1_1_sparse2_sparse.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator',['sparse_conjunction_evaluator',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fboolean_5fand_5fop_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_boolean_and_op, Lhs, Rhs &gt; &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fproduct_5fop_3c_20t1_2c_20t2_20_3e_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_product_op&lt; T1, T2 &gt;, Lhs, Rhs &gt; &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20cwisebinaryop_3c_20scalar_5fquotient_5fop_3c_20t1_2c_20t2_20_3e_2c_20lhs_2c_20rhs_20_3e_20_3e',['sparse_conjunction_evaluator&lt; CwiseBinaryOp&lt; scalar_quotient_op&lt; T1, T2 &gt;, Lhs, Rhs &gt; &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20indexbased_2c_20iteratorbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IndexBased, IteratorBased &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator_3_01_xpr_type_00_01_index_based_00_01_iterator_based_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20iteratorbased_2c_20indexbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IteratorBased, IndexBased &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator_3_01_xpr_type_00_01_iterator_based_00_01_index_based_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fconjunction_5fevaluator_3c_20xprtype_2c_20iteratorbased_2c_20iteratorbased_20_3e',['sparse_conjunction_evaluator&lt; XprType, IteratorBased, IteratorBased &gt;',['../struct_eigen_1_1internal_1_1sparse__conjunction__evaluator_3_01_xpr_type_00_01_iterator_based_00_01_iterator_based_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator',['sparse_dense_outer_product_evaluator',['../struct_eigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator_3c_20lhs_2c_20rhs_2c_20lhs_3a_3aisrowmajor_20_3e',['sparse_dense_outer_product_evaluator&lt; Lhs, Rhs, Lhs::IsRowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdense_5fouter_5fproduct_5fevaluator_3c_20lhs_2c_20rhs_2c_20rhs_3a_3aisrowmajor_20_3e',['sparse_dense_outer_product_evaluator&lt; Lhs, Rhs, Rhs::IsRowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__dense__outer__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator',['sparse_diagonal_product_evaluator',['../struct_eigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20lhs_2c_20transpose_3c_20const_20rhs_3a_3adiagonalvectortype_20_3e_2c_20lhs_3a_3aflags_20_26rowmajorbit_3fsdp_5fascwiseproduct_3asdp_5fasscalarproduct_20_3e',['sparse_diagonal_product_evaluator&lt; Lhs, Transpose&lt; const Rhs::DiagonalVectorType &gt;, Lhs::Flags &amp;RowMajorBit?SDP_AsCwiseProduct:SDP_AsScalarProduct &gt;',['../struct_eigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20rhs_2c_20lhs_3a_3adiagonalvectortype_2c_20rhs_3a_3aflags_20_26rowmajorbit_3fsdp_5fasscalarproduct_3asdp_5fascwiseproduct_20_3e',['sparse_diagonal_product_evaluator&lt; Rhs, Lhs::DiagonalVectorType, Rhs::Flags &amp;RowMajorBit?SDP_AsScalarProduct:SDP_AsCwiseProduct &gt;',['../struct_eigen_1_1internal_1_1sparse__diagonal__product__evaluator.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20sparsexprtype_2c_20diagcoefftype_2c_20sdp_5fascwiseproduct_20_3e',['sparse_diagonal_product_evaluator&lt; SparseXprType, DiagCoeffType, SDP_AsCwiseProduct &gt;',['../struct_eigen_1_1internal_1_1sparse__diagonal__product__evaluator_3_01_sparse_xpr_type_00_01_diag5c533b27b8fe485cf13e7ad699b99003.html',1,'Eigen::internal']]],
  ['sparse_5fdiagonal_5fproduct_5fevaluator_3c_20sparsexprtype_2c_20diagonalcoefftype_2c_20sdp_5fasscalarproduct_20_3e',['sparse_diagonal_product_evaluator&lt; SparseXprType, DiagonalCoeffType, SDP_AsScalarProduct &gt;',['../struct_eigen_1_1internal_1_1sparse__diagonal__product__evaluator_3_01_sparse_xpr_type_00_01_diag3ebd66799ce02a814119c716700b9642.html',1,'Eigen::internal']]],
  ['sparse_5feval',['sparse_eval',['../struct_eigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_201_2c_201_2c_20flags_20_3e',['sparse_eval&lt; T, 1, 1, Flags &gt;',['../struct_eigen_1_1internal_1_1sparse__eval_3_01_t_00_011_00_011_00_01_flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_201_2c_20cols_2c_20flags_20_3e',['sparse_eval&lt; T, 1, Cols, Flags &gt;',['../struct_eigen_1_1internal_1_1sparse__eval_3_01_t_00_011_00_01_cols_00_01_flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20rows_2c_201_2c_20flags_20_3e',['sparse_eval&lt; T, Rows, 1, Flags &gt;',['../struct_eigen_1_1internal_1_1sparse__eval_3_01_t_00_01_rows_00_011_00_01_flags_01_4.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20traits_3c_20t_20_3e_3a_3arowsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3acolsatcompiletime_2c_20evaluator_3c_20t_20_3e_3a_3aflags_20_3e',['sparse_eval&lt; T, traits&lt; T &gt;::RowsAtCompileTime, traits&lt; T &gt;::ColsAtCompileTime, evaluator&lt; T &gt;::Flags &gt;',['../struct_eigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5feval_3c_20t_2c_20traits_3c_20t_20_3e_3a_3arowsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3acolsatcompiletime_2c_20traits_3c_20t_20_3e_3a_3aflags_20_3e',['sparse_eval&lt; T, traits&lt; T &gt;::RowsAtCompileTime, traits&lt; T &gt;::ColsAtCompileTime, traits&lt; T &gt;::Flags &gt;',['../struct_eigen_1_1internal_1_1sparse__eval.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl',['sparse_matrix_block_impl',['../class_eigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_20_3e',['sparse_matrix_block_impl&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols &gt;',['../class_eigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fmatrix_5fblock_5fimpl_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_20_3e',['sparse_matrix_block_impl&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols &gt;',['../class_eigen_1_1internal_1_1sparse__matrix__block__impl.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector',['sparse_solve_triangular_selector',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20lower_2c_20colmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Lower, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__selector_3_01_lhs_00_01_rhs_00_01_mode_00_01_lower_00_01_col_major_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20lower_2c_20rowmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Lower, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__selector_3_01_lhs_00_01_rhs_00_01_mode_00_01_lower_00_01_row_major_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20upper_2c_20colmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Upper, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__selector_3_01_lhs_00_01_rhs_00_01_mode_00_01_upper_00_01_col_major_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20upper_2c_20rowmajor_20_3e',['sparse_solve_triangular_selector&lt; Lhs, Rhs, Mode, Upper, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__selector_3_01_lhs_00_01_rhs_00_01_mode_00_01_upper_00_01_row_major_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fsparse_5fselector',['sparse_solve_triangular_sparse_selector',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__sparse__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsolve_5ftriangular_5fsparse_5fselector_3c_20lhs_2c_20rhs_2c_20mode_2c_20uplo_2c_20colmajor_20_3e',['sparse_solve_triangular_sparse_selector&lt; Lhs, Rhs, Mode, UpLo, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__solve__triangular__sparse__selector_3_01_lhs_00_01_rhs_00_0103d70089ab1c1a5e4529163773532981.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector',['sparse_sparse_product_with_pruning_selector',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_a7892c8b610053f5d59f33edb611e816.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_21e1c567bb33db704730c4eb2830e598.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_3de0f703bb5ed649050c959104d3eb1b.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_8b2f3809f6470cfe6598a7debb24ca1d.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_a29c87f6ec217a6cab39d35f96e8e389.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_b0be43d8f2c00d3048196cb82593ae0c.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_e175d5ee5e029960308385b07451d28e.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fproduct_5fwith_5fpruning_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_product_with_pruning_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__product__with__pruning__selector_3_01_lhs_00_01_rhs_ac6a83f16fa8af56c1b06b928dbc0536.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector',['sparse_sparse_to_dense_product_selector',['../struct_eigen_1_1internal_1_1sparse__sparse__to__dense__product__selector.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20colmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, ColMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01_lhs_00_01_rhs_00_0b0481ed72407c1b6a48b36ffd79869ef.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20colmajor_2c_20rowmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, ColMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01_lhs_00_01_rhs_00_03ba5c23d41a3f74ec97ddc300014b4ee.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20colmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, RowMajor, ColMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01_lhs_00_01_rhs_00_08b233438bc6784cbf4bc720db2f0656b.html',1,'Eigen::internal']]],
  ['sparse_5fsparse_5fto_5fdense_5fproduct_5fselector_3c_20lhs_2c_20rhs_2c_20resulttype_2c_20rowmajor_2c_20rowmajor_20_3e',['sparse_sparse_to_dense_product_selector&lt; Lhs, Rhs, ResultType, RowMajor, RowMajor &gt;',['../struct_eigen_1_1internal_1_1sparse__sparse__to__dense__product__selector_3_01_lhs_00_01_rhs_00_01573c79e134c90f065c2aee6c07fd478.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl',['sparse_time_dense_product_impl',['../struct_eigen_1_1internal_1_1sparse__time__dense__product__impl.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20alphatype_2c_20colmajor_2c_20true_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, AlphaType, ColMajor, true &gt;',['../struct_eigen_1_1internal_1_1sparse__time__dense__product__impl_3_01_sparse_lhs_type_00_01_dense_4902bcccfe44923f57955b34ebedf211.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20colmajor_2c_20false_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, ColMajor, false &gt;',['../struct_eigen_1_1internal_1_1sparse__time__dense__product__impl_3_01_sparse_lhs_type_00_01_dense_67299fc86a44049a87b7e209695d23ff.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20rowmajor_2c_20false_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, false &gt;',['../struct_eigen_1_1internal_1_1sparse__time__dense__product__impl_3_01_sparse_lhs_type_00_01_dense_14133348dce4820dcfa39d8f4e0ae837.html',1,'Eigen::internal']]],
  ['sparse_5ftime_5fdense_5fproduct_5fimpl_3c_20sparselhstype_2c_20denserhstype_2c_20denserestype_2c_20typename_20denserestype_3a_3ascalar_2c_20rowmajor_2c_20true_20_3e',['sparse_time_dense_product_impl&lt; SparseLhsType, DenseRhsType, DenseResType, typename DenseResType::Scalar, RowMajor, true &gt;',['../struct_eigen_1_1internal_1_1sparse__time__dense__product__impl_3_01_sparse_lhs_type_00_01_dense_b414480199bc806c66dca70961af5e2d.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector',['sparse_vector_assign_selector',['../struct_eigen_1_1internal_1_1sparse__vector__assign__selector.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5finner_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_Inner &gt;',['../struct_eigen_1_1internal_1_1sparse__vector__assign__selector_3_01_dest_00_01_src_00_01_s_v_a___inner_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5fouter_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_Outer &gt;',['../struct_eigen_1_1internal_1_1sparse__vector__assign__selector_3_01_dest_00_01_src_00_01_s_v_a___outer_01_4.html',1,'Eigen::internal']]],
  ['sparse_5fvector_5fassign_5fselector_3c_20dest_2c_20src_2c_20sva_5fruntimeswitch_20_3e',['sparse_vector_assign_selector&lt; Dest, Src, SVA_RuntimeSwitch &gt;',['../struct_eigen_1_1internal_1_1sparse__vector__assign__selector_3_01_dest_00_01_src_00_01_s_v_a___runtime_switch_01_4.html',1,'Eigen::internal']]],
  ['sparsecompressedbase',['SparseCompressedBase',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseCompressedBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseCompressedBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseCompressedBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_compressed_base.html',1,'Eigen']]],
  ['sparsedenseouterproduct',['SparseDenseOuterProduct',['../class_eigen_1_1_sparse_dense_outer_product.html',1,'Eigen']]],
  ['sparsedenseproductreturntype',['SparseDenseProductReturnType',['../struct_eigen_1_1_sparse_dense_product_return_type.html',1,'Eigen']]],
  ['sparsediagonalproduct',['SparseDiagonalProduct',['../class_eigen_1_1_sparse_diagonal_product.html',1,'Eigen']]],
  ['sparsefunctor',['SparseFunctor',['../struct_eigen_1_1_sparse_functor.html',1,'Eigen']]],
  ['sparsefunctor_3c_20scalar_2c_20int_20_3e',['SparseFunctor&lt; Scalar, int &gt;',['../struct_eigen_1_1_sparse_functor.html',1,'Eigen']]],
  ['sparsegaussiantest',['sparseGaussianTest',['../structsparse_gaussian_test.html',1,'']]],
  ['sparselu',['SparseLU',['../class_eigen_1_1_sparse_l_u.html',1,'Eigen']]],
  ['sparseluimpl',['SparseLUImpl',['../class_sparse_l_u_impl.html',1,'SparseLUImpl&lt; Scalar, StorageIndex &gt;'],['../class_eigen_1_1internal_1_1_sparse_l_u_impl.html',1,'Eigen::internal::SparseLUImpl&lt; Scalar, StorageIndex &gt;']]],
  ['sparseluimpl_3c_20_5fmatrixtype_3a_3ascalar_2c_20_5fmatrixtype_3a_3astorageindex_20_3e',['SparseLUImpl&lt; _MatrixType::Scalar, _MatrixType::StorageIndex &gt;',['../class_eigen_1_1internal_1_1_sparse_l_u_impl.html',1,'Eigen::internal']]],
  ['sparselumatrixlreturntype',['SparseLUMatrixLReturnType',['../struct_eigen_1_1_sparse_l_u_matrix_l_return_type.html',1,'Eigen']]],
  ['sparselumatrixureturntype',['SparseLUMatrixUReturnType',['../struct_eigen_1_1_sparse_l_u_matrix_u_return_type.html',1,'Eigen']]],
  ['sparsemapbase',['SparseMapBase',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_20_3e',['SparseMapBase&lt; Derived &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20readonlyaccessors_20_3e',['SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;',['../class_eigen_1_1_sparse_map_base_3_01_derived_00_01_read_only_accessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20writeaccessors_20_3e',['SparseMapBase&lt; Derived, WriteAccessors &gt;',['../class_eigen_1_1_sparse_map_base_3_01_derived_00_01_write_accessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20map_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Map&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20map_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Map&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsemapbase_3c_20ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseMapBase&lt; Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1_sparse_map_base.html',1,'Eigen']]],
  ['sparsematrix',['SparseMatrix',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20double_20_3e',['SparseMatrix&lt; double &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_20_3e',['SparseMatrix&lt; Scalar &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_20_3e',['SparseMatrix&lt; Scalar, ColMajor &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20int_20_3e',['SparseMatrix&lt; Scalar, ColMajor, int &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, ColMajor, StorageIndex &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_20_3e',['SparseMatrix&lt; Scalar, RowMajor &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_2c_20storageindex_20_3e',['SparseMatrix&lt; Scalar, RowMajor, StorageIndex &gt;',['../class_eigen_1_1_sparse_matrix.html',1,'Eigen']]],
  ['sparsematrixbase',['SparseMatrixBase',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, true &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrix_3c_20_5fscalar_2c_20_5fblockatcompiletime_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; BlockSparseMatrix&lt; _Scalar, _BlockAtCompileTime, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrix_3c_20_5fscalar_2c_20_5fblockatcompiletime_2c_20_5foptions_2c_20storageindex_20_3e_20_3e',['SparseMatrixBase&lt; BlockSparseMatrix&lt; _Scalar, _BlockAtCompileTime, _Options, StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20blocksparsematrixt_20_3e',['SparseMatrixBase&lt; BlockSparseMatrixT &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20cwisebinaryop_3c_20binaryop_2c_20lhs_2c_20rhs_20_3e_20_3e',['SparseMatrixBase&lt; CwiseBinaryOp&lt; BinaryOp, Lhs, Rhs &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20dynamicsparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; DynamicSparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e',['SparseMatrixBase&lt; SparseVector&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparseview_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; SparseView&lt; MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e',['SparseMatrixBase&lt; Transpose&lt; MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20triangularview_3c_20matrixtype_2c_20mode_20_3e_20_3e',['SparseMatrixBase&lt; TriangularView&lt; MatrixType, Mode &gt; &gt;',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparseqr',['SparseQR',['../class_eigen_1_1_sparse_q_r.html',1,'Eigen']]],
  ['sparseqr_5fqproduct',['SparseQR_QProduct',['../struct_eigen_1_1_sparse_q_r___q_product.html',1,'Eigen']]],
  ['sparseqrmatrixqreturntype',['SparseQRMatrixQReturnType',['../struct_eigen_1_1_sparse_q_r_matrix_q_return_type.html',1,'Eigen']]],
  ['sparseqrmatrixqtransposereturntype',['SparseQRMatrixQTransposeReturnType',['../struct_eigen_1_1_sparse_q_r_matrix_q_transpose_return_type.html',1,'Eigen']]],
  ['sparserefbase',['SparseRefBase',['../class_eigen_1_1internal_1_1_sparse_ref_base.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20const_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; const SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1internal_1_1_sparse_ref_base.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20const_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; const SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1internal_1_1_sparse_ref_base.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20sparsematrix_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; SparseMatrix&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1internal_1_1_sparse_ref_base.html',1,'Eigen::internal']]],
  ['sparserefbase_3c_20ref_3c_20sparsevector_3c_20matscalar_2c_20matoptions_2c_20matindex_20_3e_2c_20options_2c_20stridetype_20_3e_20_3e',['SparseRefBase&lt; Ref&lt; SparseVector&lt; MatScalar, MatOptions, MatIndex &gt;, Options, StrideType &gt; &gt;',['../class_eigen_1_1internal_1_1_sparse_ref_base.html',1,'Eigen::internal']]],
  ['sparseselfadjoint2sparse',['SparseSelfAdjoint2Sparse',['../struct_eigen_1_1internal_1_1_sparse_self_adjoint2_sparse.html',1,'Eigen::internal']]],
  ['sparseselfadjointshape',['SparseSelfAdjointShape',['../struct_eigen_1_1internal_1_1_sparse_self_adjoint_shape.html',1,'Eigen::internal']]],
  ['sparseselfadjointview',['SparseSelfAdjointView',['../class_eigen_1_1_sparse_self_adjoint_view.html',1,'Eigen']]],
  ['sparseshape',['SparseShape',['../struct_eigen_1_1_sparse_shape.html',1,'Eigen']]],
  ['sparsesolverbase',['SparseSolverBase',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20bicgstab_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; BiCGSTAB&lt; _MatrixType, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmoddecomposition_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodDecomposition&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsimplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSimplicialLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmodsupernodalllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; CholmodSupernodalLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20conjugategradient_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; ConjugateGradient&lt; _MatrixType, _UpLo, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20dgmres_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; DGMRES&lt; _MatrixType, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20gmres_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; GMRES&lt; _MatrixType, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletecholesky_3c_20scalar_2c_20_5fuplo_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; IncompleteCholesky&lt; Scalar, _UpLo, _OrderingType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelu_3c_20_5fscalar_20_3e_20_3e',['SparseSolverBase&lt; IncompleteLU&lt; _Scalar &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20incompletelut_3c_20_5fscalar_2c_20_5fstorageindex_20_3e_20_3e',['SparseSolverBase&lt; IncompleteLUT&lt; _Scalar, _StorageIndex &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20leastsquaresconjugategradient_3c_20_5fmatrixtype_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; LeastSquaresConjugateGradient&lt; _MatrixType, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20minres_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fpreconditioner_20_3e_20_3e',['SparseSolverBase&lt; MINRES&lt; _MatrixType, _UpLo, _Preconditioner &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisoldlt_3c_20matrixtype_2c_20options_20_3e_20_3e',['SparseSolverBase&lt; PardisoLDLT&lt; MatrixType, Options &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisollt_3c_20matrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PardisoLLT&lt; MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pardisolu_3c_20matrixtype_20_3e_20_3e',['SparseSolverBase&lt; PardisoLU&lt; MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLDLT&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixllt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e',['SparseSolverBase&lt; PastixLLT&lt; _MatrixType, _UpLo &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20pastixlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; PastixLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SparseSolverBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparselu_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseLU&lt; _MatrixType, _OrderingType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20sparseqr_3c_20_5fmatrixtype_2c_20_5forderingtype_20_3e_20_3e',['SparseSolverBase&lt; SparseQR&lt; _MatrixType, _OrderingType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20spqr_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SPQR&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; SuperLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20umfpacklu_3c_20_5fmatrixtype_20_3e_20_3e',['SparseSolverBase&lt; UmfPackLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_sparse_solver_base.html',1,'Eigen']]],
  ['sparsesparseproduct',['SparseSparseProduct',['../class_eigen_1_1_sparse_sparse_product.html',1,'Eigen']]],
  ['sparsesparseproductreturntype',['SparseSparseProductReturnType',['../struct_eigen_1_1_sparse_sparse_product_return_type.html',1,'Eigen']]],
  ['sparsesymmetricpermutationproduct',['SparseSymmetricPermutationProduct',['../class_eigen_1_1_sparse_symmetric_permutation_product.html',1,'Eigen']]],
  ['sparsetimedenseproduct',['SparseTimeDenseProduct',['../class_eigen_1_1_sparse_time_dense_product.html',1,'Eigen']]],
  ['sparsetransposeimpl',['SparseTransposeImpl',['../class_eigen_1_1internal_1_1_sparse_transpose_impl.html',1,'Eigen::internal']]],
  ['sparsetransposeimpl_3c_20matrixtype_20_3e',['SparseTransposeImpl&lt; MatrixType &gt;',['../class_eigen_1_1internal_1_1_sparse_transpose_impl.html',1,'Eigen::internal']]],
  ['sparsetransposeimpl_3c_20matrixtype_2c_20compressedaccessbit_20_3e',['SparseTransposeImpl&lt; MatrixType, CompressedAccessBit &gt;',['../class_eigen_1_1internal_1_1_sparse_transpose_impl_3_01_matrix_type_00_01_compressed_access_bit_01_4.html',1,'Eigen::internal']]],
  ['sparsetriangularshape',['SparseTriangularShape',['../struct_eigen_1_1internal_1_1_sparse_triangular_shape.html',1,'Eigen::internal']]],
  ['sparsevector',['SparseVector',['../class_eigen_1_1_sparse_vector.html',1,'Eigen']]],
  ['sparseview',['SparseView',['../class_eigen_1_1_sparse_view.html',1,'Eigen']]],
  ['spline',['Spline',['../class_eigen_1_1_spline.html',1,'Eigen']]],
  ['splinefitting',['SplineFitting',['../struct_eigen_1_1_spline_fitting.html',1,'Eigen']]],
  ['splinetraits',['SplineTraits',['../struct_eigen_1_1_spline_traits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_20_3e',['SplineTraits&lt; Spline &gt;',['../struct_eigen_1_1_spline_traits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt; &gt;',['../struct_eigen_1_1_spline_traits.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_2c_20_5fderivativeorder_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt;, _DerivativeOrder &gt;',['../struct_eigen_1_1_spline_traits_3_01_spline_3_01___scalar_00_01___dim_00_01___degree_01_4_00_01___derivative_order_01_4.html',1,'Eigen']]],
  ['splinetraits_3c_20spline_3c_20_5fscalar_2c_20_5fdim_2c_20_5fdegree_20_3e_2c_20dynamic_20_3e',['SplineTraits&lt; Spline&lt; _Scalar, _Dim, _Degree &gt;, Dynamic &gt;',['../struct_eigen_1_1_spline_traits_3_01_spline_3_01___scalar_00_01___dim_00_01___degree_01_4_00_01_dynamic_01_4.html',1,'Eigen']]],
  ['spqr',['SPQR',['../class_eigen_1_1_s_p_q_r.html',1,'Eigen']]],
  ['spqr_5fqproduct',['SPQR_QProduct',['../struct_eigen_1_1_s_p_q_r___q_product.html',1,'Eigen']]],
  ['spqrmatrixqreturntype',['SPQRMatrixQReturnType',['../struct_eigen_1_1_s_p_q_r_matrix_q_return_type.html',1,'Eigen']]],
  ['spqrmatrixqtransposereturntype',['SPQRMatrixQTransposeReturnType',['../struct_eigen_1_1_s_p_q_r_matrix_q_transpose_return_type.html',1,'Eigen']]],
  ['state',['state',['../structstate.html',1,'']]],
  ['statecontroller',['StateController',['../class_state_controller.html',1,'']]],
  ['static_5fassertion',['static_assertion',['../struct_eigen_1_1internal_1_1static__assertion.html',1,'Eigen::internal']]],
  ['static_5fassertion_3c_20true_20_3e',['static_assertion&lt; true &gt;',['../struct_eigen_1_1internal_1_1static__assertion_3_01true_01_4.html',1,'Eigen::internal']]],
  ['static_5fsize_5fgenerator',['static_size_generator',['../structstatic__size__generator.html',1,'']]],
  ['static_5fsize_5fgenerator_3c_201_2c_20perf_5fanalyzer_2c_20action_2c_20interface_20_3e',['static_size_generator&lt; 1, Perf_Analyzer, Action, Interface &gt;',['../structstatic__size__generator_3_011_00_01_perf___analyzer_00_01_action_00_01_interface_01_4.html',1,'']]],
  ['static_5ftree_5fdesc_5fs',['static_tree_desc_s',['../structstatic__tree__desc__s.html',1,'']]],
  ['static_5fval',['static_val',['../struct_eigen_1_1internal_1_1static__val.html',1,'Eigen::internal']]],
  ['staticif',['StaticIf',['../structutility_1_1tuple_1_1_static_if.html',1,'utility::tuple']]],
  ['staticif_3c_20true_2c_20t_20_3e',['StaticIf&lt; true, T &gt;',['../structutility_1_1tuple_1_1_static_if_3_01true_00_01_t_01_4.html',1,'utility::tuple']]],
  ['staticsgroup',['StaticSGroup',['../class_eigen_1_1_static_s_group.html',1,'Eigen']]],
  ['stdmaptraits',['StdMapTraits',['../struct_eigen_1_1_std_map_traits.html',1,'Eigen']]],
  ['stem_5ffunction',['stem_function',['../struct_eigen_1_1internal_1_1stem__function.html',1,'Eigen::internal']]],
  ['stl_5finterface',['STL_interface',['../class_s_t_l__interface.html',1,'']]],
  ['stl_5fperf_5fanalyzer',['STL_Perf_Analyzer',['../class_s_t_l___perf___analyzer.html',1,'']]],
  ['stl_5ftimer',['STL_Timer',['../class_s_t_l___timer.html',1,'']]],
  ['stlthreadenvironment',['StlThreadEnvironment',['../struct_eigen_1_1_stl_thread_environment.html',1,'Eigen']]],
  ['storage_5fkind_5fto_5fevaluator_5fkind',['storage_kind_to_evaluator_kind',['../struct_eigen_1_1internal_1_1storage__kind__to__evaluator__kind.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fevaluator_5fkind_3c_20sparse_20_3e',['storage_kind_to_evaluator_kind&lt; Sparse &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__evaluator__kind_3_01_sparse_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape',['storage_kind_to_shape',['../struct_eigen_1_1internal_1_1storage__kind__to__shape.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20dense_20_3e',['storage_kind_to_shape&lt; Dense &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_dense_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20diagonalshape_20_3e',['storage_kind_to_shape&lt; DiagonalShape &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_diagonal_shape_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20permutationstorage_20_3e',['storage_kind_to_shape&lt; PermutationStorage &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_permutation_storage_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20solverstorage_20_3e',['storage_kind_to_shape&lt; SolverStorage &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_solver_storage_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20sparse_20_3e',['storage_kind_to_shape&lt; Sparse &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_sparse_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20transpositionsstorage_20_3e',['storage_kind_to_shape&lt; TranspositionsStorage &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_transpositions_storage_01_4.html',1,'Eigen::internal']]],
  ['stride',['Stride',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e',['Stride&lt; 0, Value &gt;',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stride_3c_20stridetype_3a_3aouterstrideatcompiletime_2c_20stridetype_3a_3ainnerstrideatcompiletime_20_3e',['Stride&lt; StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime &gt;',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e',['Stride&lt; Value, 0 &gt;',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stridedalignedmaptype',['StridedAlignedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_aligned_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstalignedmaptype',['StridedConstAlignedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_const_aligned_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstmaptype',['StridedConstMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_const_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedmaptype',['StridedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['strip_5fidentities',['strip_identities',['../struct_eigen_1_1internal_1_1group__theory_1_1strip__identities.html',1,'Eigen::internal::group_theory']]],
  ['strip_5fidentities_3c_20equality_2c_20id_2c_20type_5flist_3c_20eigen_5ftpl_5fpp_5fspec_5fhack_5fuse_28ts_29_3e_20_3e',['strip_identities&lt; Equality, id, type_list&lt; EIGEN_TPL_PP_SPEC_HACK_USE(ts)&gt; &gt;',['../struct_eigen_1_1internal_1_1group__theory_1_1strip__identities_3_01_equality_00_01id_00_01type__910db64a8d6fcf148be1d9764b935ba6.html',1,'Eigen::internal::group_theory']]],
  ['strip_5fidentities_3c_20equality_2c_20id_2c_20type_5flist_3c_20t_2c_20ts_2e_2e_2e_20_3e_20_3e',['strip_identities&lt; Equality, id, type_list&lt; t, ts... &gt; &gt;',['../struct_eigen_1_1internal_1_1group__theory_1_1strip__identities_3_01_equality_00_01id_00_01type__f08cc45c8ea5d12fcc4f4eb6bf8771ff.html',1,'Eigen::internal::group_theory']]],
  ['strtype',['StrType',['../class_h5_1_1_str_type.html',1,'H5']]],
  ['sub',['sub',['../struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_dense_shape_00_01_de81a9bc57ab96e388cf835587b3174f05.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['sub_5fassign_5fop',['sub_assign_op',['../struct_eigen_1_1internal_1_1sub__assign__op.html',1,'Eigen::internal']]],
  ['subset_5fd',['subset_d',['../structsubset__d.html',1,'']]],
  ['subset_5ft',['subset_t',['../structsubset__t.html',1,'']]],
  ['sum_5fop',['sum_op',['../struct_eigen_1_1internal_1_1sum__op.html',1,'Eigen::internal']]],
  ['sumreducer',['SumReducer',['../struct_eigen_1_1internal_1_1_sum_reducer.html',1,'Eigen::internal']]],
  ['superlu',['SuperLU',['../class_eigen_1_1_super_l_u.html',1,'Eigen']]],
  ['superlubase',['SuperLUBase',['../class_eigen_1_1_super_l_u_base.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperLU&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_super_l_u_base.html',1,'Eigen']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal',['svd_precondition_2x2_block_to_be_real',['../struct_eigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real.html',1,'Eigen::internal']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal_3c_20matrixtype_2c_20qrpreconditioner_2c_20false_20_3e',['svd_precondition_2x2_block_to_be_real&lt; MatrixType, QRPreconditioner, false &gt;',['../struct_eigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real_3_01_matrix_type_00_01_q076cf26720930d18ea7d222bbee662fd.html',1,'Eigen::internal']]],
  ['svd_5fprecondition_5f2x2_5fblock_5fto_5fbe_5freal_3c_20matrixtype_2c_20qrpreconditioner_2c_20true_20_3e',['svd_precondition_2x2_block_to_be_real&lt; MatrixType, QRPreconditioner, true &gt;',['../struct_eigen_1_1internal_1_1svd__precondition__2x2__block__to__be__real_3_01_matrix_type_00_01_qb58fa819a3391e7d55d98ccdc14db9e4.html',1,'Eigen::internal']]],
  ['svdbase',['SVDBase',['../class_eigen_1_1_s_v_d_base.html',1,'Eigen']]],
  ['svdbase_3c_20bdcsvd_3c_20_5fmatrixtype_20_3e_20_3e',['SVDBase&lt; BDCSVD&lt; _MatrixType &gt; &gt;',['../class_eigen_1_1_s_v_d_base.html',1,'Eigen']]],
  ['svdbase_3c_20jacobisvd_3c_20_5fmatrixtype_2c_20qrpreconditioner_20_3e_20_3e',['SVDBase&lt; JacobiSVD&lt; _MatrixType, QRPreconditioner &gt; &gt;',['../class_eigen_1_1_s_v_d_base.html',1,'Eigen']]],
  ['swap_5fassign_5fop',['swap_assign_op',['../struct_eigen_1_1internal_1_1swap__assign__op.html',1,'Eigen::internal']]],
  ['swap_5fassign_5fop_3c_20dstevaluatortypet_3a_3ascalar_20_3e',['swap_assign_op&lt; DstEvaluatorTypeT::Scalar &gt;',['../struct_eigen_1_1internal_1_1swap__assign__op.html',1,'Eigen::internal']]],
  ['swapwrapper',['SwapWrapper',['../class_eigen_1_1_swap_wrapper.html',1,'Eigen']]],
  ['syclgenericbufferreducer',['syclGenericBufferReducer',['../struct_eigen_1_1internal_1_1sycl_generic_buffer_reducer.html',1,'Eigen::internal']]],
  ['symlink_5ftrav_5fpath_5ft',['symlink_trav_path_t',['../structsymlink__trav__path__t.html',1,'']]],
  ['symlink_5ftrav_5ft',['symlink_trav_t',['../structsymlink__trav__t.html',1,'']]],
  ['symm_5fpack_5flhs',['symm_pack_lhs',['../struct_eigen_1_1internal_1_1symm__pack__lhs.html',1,'Eigen::internal']]],
  ['symm_5fpack_5frhs',['symm_pack_rhs',['../struct_eigen_1_1internal_1_1symm__pack__rhs.html',1,'Eigen::internal']]],
  ['symmetry',['Symmetry',['../struct_eigen_1_1_symmetry.html',1,'Eigen']]],
  ['sz_5fcom_5ft_5fs',['SZ_com_t_s',['../struct_s_z__com__t__s.html',1,'']]],
  ['sz_5fhidden_5fdata_5fs',['sz_hidden_data_s',['../structsz__hidden__data__s.html',1,'']]],
  ['sz_5fstream_5fs',['sz_stream_s',['../structsz__stream__s.html',1,'']]]
];
